### ISSUE TITLE
error TS2769: No overload matches this call. with useQuery.

### ISSUE THREAD

**Issue by weicong** [kubb-project/kubb#193]
![image](https://user-images.githubusercontent.com/1157868/230870057-49a88870-5d8e-41fc-b154-f5c327e029f7.png)
![image](https://user-images.githubusercontent.com/1157868/230870105-0701bc43-d9cc-40a2-bc71-0b02b2894319.png)

**Comment by stijnvanhulle** [comment]
This is normally already fixed but it was not yet included in a new version. That new version will be published later today :)

**Comment by stijnvanhulle** [comment]
Fixed in version  [1.0.0-beta.12](https://www.npmjs.com/package/@kubb/core/v/1.0.0-beta.12)

**Comment by weicong** [comment]
Maybe the problem is related to the version of `@tanstack/react-query`

![1681174772162](https://user-images.githubusercontent.com/1157868/231028134-2e69f7d4-686f-4c30-8f5e-85cc733965a6.png)

**Comment by weicong** [comment]
@stijnvanhulle https://github.com/weicong/kubb-gen-test.git

 I also have a problem, `exportAs` doesn't work.

**Comment by stijnvanhulle** [comment]
@weicong Tried your repo and the `exportAs` was working for me, not sure what is going wrong here :(

**Comment by weicong** [comment]
@stijnvanhulle I'm using Windows, does that matter? 😭

**Comment by weicong** [comment]
@stijnvanhulle I cloned the code from https://github.com/kubb-project/kubb.git and compiled it

![image](https://user-images.githubusercontent.com/1157868/231510340-4eb1bbdf-39c8-46b8-9dcc-bf2d85f571b4.png)

**Comment by stijnvanhulle** [comment]
@weicong Hmm seems indeed to be a Windows issue(/ vs \). I will create another version and come back to you :)

**Comment by weicong** [comment]
@stijnvanhulle  `exportAs` works well, and `error TS2769` no longer occurs, thanks.

**Comment by weicong** [comment]
@stijnvanhulle `error TS2769`  has appeared again in v1.0.0-beta.15 ;

```ts
import type { useQuery, QueryKey, UseQueryResult, UseQueryOptions, QueryOptions } from "@tanstack/react-query";
import type { useMutation, UseMutationOptions } from "@tanstack/react-query";
```
and, useQuery, useMutation is not a type,

perhaps, it is related to Windows OS again.

![image](https://user-images.githubusercontent.com/1157868/232330264-01c931be-e4af-465b-a0f8-d9f9c01bc5c1.png)

**Comment by stijnvanhulle** [comment]
@weicong Sorry, I made a small mistake, should be fixed with beta 17
