### ISSUE TITLE
kubb is exporting types but not hooks neither tanstack query nor swr

### ISSUE THREAD

**Issue by omarkhatibco** [kubb-project/kubb#196]
Hey, 

I was trying kubb today with our API, it was unable to generate any hooks only the  types.

I tried both swr and react query + json file and yaml file

here is a sandbox for testing based on your sandbox
https://codesandbox.io/p/sandbox/jovial-artem-qgz29y?file=%2Fbackend.yaml

**Comment by stijnvanhulle** [comment]
@omarkhatibco Hi, thanks for trying out. I had a look and it seems we had a hard check based on `operationId` which is not included in your Swagger(it's also an optional field). I will open a PR  soon that will resolve that :)

**Comment by stijnvanhulle** [comment]
Version `1.0.0-beta.13` will resolve your issue :)

**Comment by omarkhatibco** [comment]
@stijnvanhulle  thanks for the quick fix
