### ISSUE TITLE
generation error: object is being an array in typescript

### ISSUE THREAD

**Issue by omarkhatibco** [kubb-project/kubb#204]
Hey again, 

so I was checking the generated types and discovered that there is a model inside the swagger is being transferred to array of the same type 
so in json file 

```json
              "references": {
                "type": "object",
                "nullable": false,
                "items": { "$ref": "#/components/schemas/references" }
              },
              "suppliers": { "type": "array", "items": { "$ref": "#/components/schemas/supplier" } }
```
and in ts model it's 

```ts
  /**
     * @type object
     */
    references: References[]
    /**
     * @type array
     */
    suppliers: Supplier[]
```

another example 

```ts
  /**
   * @type object
   */
  quoted_price: Pricing[]
  /**
   * @type object | undefined
   */
  booking_price?: Pricing[] | undefined
  /**
   * @description The latest booking status that this room has
   * @type string
   */
```

link for testing: https://codesandbox.io/p/sandbox/jovial-artem-qgz29y?file=%2Fbackend.json&selection=%5B%7B%22endColumn%22%3A101%2C%22endLineNumber%22%3A75%2C%22startColumn%22%3A1%2C%22startLineNumber%22%3A70%7D%5D

thank you
Omar

**Comment by stijnvanhulle** [comment]
Hi,

 `"type": "object",` and `"items": { "$ref": "#/components/schemas/references" }` cannot work together because `items` is preserved to be used with as type **array**.

The following will be valid:
```
"references": {
     $ref": "#/components/schemas/references"
 },
"suppliers": { "type": "array", "items": { "$ref": "#/components/schemas/supplier" } }
```

https://spec.openapis.org/oas/v3.1.0#specifying-schema-dialects

**Comment by omarkhatibco** [comment]
@stijnvanhulle thank you, it was from our Backend.
