### ISSUE TITLE
some problems about groupBy, exportAs

### ISSUE THREAD

**Issue by weicong** [kubb-project/kubb#206]
here is my config
```ts
import { defineConfig } from "@kubb/core";
import createSwagger from "@kubb/swagger";
import createSwaggerTS from "@kubb/swagger-ts";
import createSwaggerTanstackQuery from "@kubb/swagger-tanstack-query";

export default defineConfig(async () => {
  const client = "./src/utils/axios-client.ts";

  return {
    root: ".",
    input: { path: "swagger.json" },
    output: { path: "./src/api", clean: true },
    plugins: [
      createSwagger({ output: false }),
      createSwaggerTS({
        output: "models",
        groupBy: {
          type: "tag",
          output: "models/{{tag}}Models",
        },
        enumType: "enum",
      }),
      createSwaggerTanstackQuery({
        output: "hooks",
        groupBy: {
          type: "tag",
          output: "hooks/{{tag}}Hooks",
          exportAs: "{{tag}}Hooks",
        },
        client,
      }),
    ],
  };
});
```

and, output 
![1](https://user-images.githubusercontent.com/1157868/231685543-c93e77df-4e00-45c1-b2e4-225c50bc9bbc.png)

but, i want
![2](https://user-images.githubusercontent.com/1157868/231685650-a15507a0-896e-4fcc-9e2c-45034cb7a666.png)

1. `export * as {{tag}}Hooks from "./hooks/{{tag}}Hooks";` in ./index.ts move to ./hooks/index.ts;
2.  remove `export * from "./{tag}Models";` in ./models/index.ts when set `groupBy.type: "tag"`,  avoid the same object name.

codes: https://github.com/weicong/kubb-gen-test.git

thanks.

**Comment by stijnvanhulle** [comment]
@weicong version 'V1.0.0-BETA.15' should contain the desired behaviour 😃

**Comment by weicong** [comment]
@stijnvanhulle ❤️Thank you so much for your work.

The 2nd question still bothers me a little bit. Some of the operationIds given by our backend are the same, such as
`Create`, `Update`, `Remove`, `Get`. In this case, there will be conflicts in the generated `.\models\index.ts`  file. Can it be like this, if there is such a situation, don’t output a few lines in the `.\models\index.ts`  file, do you think it is possible, thank you

![image](https://user-images.githubusercontent.com/1157868/232356696-39d5a28b-a6a6-4d59-a81c-9532fb86091b.png)

codes: https://github.com/weicong/kubb-gen-test (use 1.0.0-beta.17)

**Comment by stijnvanhulle** [comment]
@weicong OperationIds should be unique inside of the Swagger/OpenAPI file. `operationId is an optional unique string used to identify an operation. If provided, these IDs must be unique among all operations described in your API.`, see https://swagger.io/docs/specification/paths-and-operations/?sbsearch=operationid.
