### ISSUE TITLE
Is there a way to convert asConst enums to PascalCase?

### ISSUE THREAD

**Issue by la55u** [kubb-project/kubb#220]
Instead of this:
```ts
export const bankTransferType = {
  INTERNAL: 'INTERNAL',
  EXTERNAL: 'EXTERNAL',
} as const;
```

I'd prefer to have this:
```ts
export const BankTransferType = {
  INTERNAL: 'INTERNAL',
  EXTERNAL: 'EXTERNAL',
} as const;
```

or `BANK_TRANSFER_TYPE`.

IS there any way to achieve this currently?

Thank you, very nice lib!

**Comment by stijnvanhulle** [comment]
Added a new property/setting to the `enumType` of the config of `swagger-ts`. 
See https://kubb-git-feat-aspascalconst-kubb.vercel.app/plugins/swagger-ts#enumtype. 

Will be merged in the following PR: https://github.com/kubb-project/kubb/pull/223

**Comment by la55u** [comment]
Love U <3
