### ISSUE TITLE
cli: hide file path

### ISSUE THREAD

**Issue by AlexMunoz** [kubb-project/kubb#253]
Hello, Nice to see you are back 👍 

Could be possible to have some flag to hide the file path from the cli output or the spinners?
Maybe using flag to enable or disable the isSilent opt of ora. 

Context: I'm using a url with a private access token as input path and would like it not to be logged. 

Thanks for you work, kubb is really cool!

**Comment by stijnvanhulle** [comment]
Thanks for using it, really like to see it being used 🙌🏽.

I will do the following: logLevel `silent` will make sure that info related to which file is getting used is hidden.

### info
```
'logLevel': 'info'
```
<img width="642" alt="Screenshot 2023-06-06 at 22 51 12" src="https://github.com/kubb-project/kubb/assets/5904681/901c0331-cf3e-4afe-a1f8-8fd5fd57d801">

### silent


```
'logLevel': 'silent' // by default
```
<img width="541" alt="Screenshot 2023-06-06 at 22 51 00" src="https://github.com/kubb-project/kubb/assets/5904681/b0bc8de9-8013-4d05-b778-0890b4665b9e">
