### ISSUE TITLE
@kubb/swagger-zod default export 

### ISSUE THREAD

**Issue by maissenayed** [kubb-project/kubb#263]
Hey!! , so when trying to generate zod validation from schema , the code is always generated with Zod default import

```
import z from 'zod';

export const petSchema = z.object({
    id: z.number(),
    name: z.string(),
    tag: z.string().optional(),
});
```

But `Zod` don"t have a default export it should always be
 
`import {z} from 'zod';`

**Comment by stijnvanhulle** [comment]
<img width="248" alt="Screenshot 2023-06-08 at 17 22 44" src="https://github.com/kubb-project/kubb/assets/5904681/e07a749a-4bb5-419e-9c82-cacaf5f36bb0">

Normally this should not be an issue with that `Zod` is also using a default export
