### ISSUE TITLE
Generated mutations by @kubb/swagger-tanstack-query don't add types by to variables

### ISSUE THREAD

**Issue by Jesus-Hernandez23** [kubb-project/kubb#274]
### What version of `kubb` is running?

1.1.8

### What platform is your computer?

Windows

### What steps can reproduce the bug?

I'm using this configuration for generate code: 
```
export default defineConfig({
  root: '.',
  input: {
    path: 'http://localhost:5281/swagger/v1/swagger.json',
  },
  output: {
    path: './src/api',
    clean: true,
  },
  plugins: [
    createSwagger({ output: false }),
    ZodGenerator({ output: './validator' }),
    createSwaggerTS({}),
    createFaker({}),
    createSwaggerTanstackQuery({
      // client: 'hooks/useCustomClient.ts',
    }),
  ],
});

```

and run this comand:  `kubb --config ./kubb.config.ts`

then it generates this code for usePostAPIv!Accountants(): 
```
import { useMutation, UseMutationOptions } from '@tanstack/react-query';
import client from '@kubb/swagger-client/client';
import type { PostApiV1AccountantsMutationResponse } from '.\\..\\models\\PostApiV1Accountants';

/**
 * @link /api/v1/Accountants
 */
export function usePostApiV1Accountants<TData = PostApiV1AccountantsMutationResponse, TError = unknown>(options?: {
  mutation?: UseMutationOptions<TData, TError>;
}) {
  const { mutation: mutationOptions } = options ?? {};

  return useMutation<TData, TError>({
    mutationFn: () => {
      return client<TData, TError>({
        method: 'post',
        url: `/api/v1/Accountants`,
      });
    },
    ...mutationOptions,
  });
}

```

### What is the expected behavior?

The variable parameter of the mutate function returned by useMutation should have the corresponding type definition instead of void.
![Screenshot 2023-06-11 011319](https://github.com/kubb-project/kubb/assets/83924460/e2e6e167-cdf9-4ef4-a94d-ebea9d046705)

### What do you see instead?

It throws a TypeScript error because the parameters are not defined.

```
Argument of type '{ data: { amount: number; reason: string; type: "0" | "1"; note?: string | null | undefined; }; }' is not assignable to parameter of type 'void'.ts(2345)
(property) data: {
    amount: number;
    reason: string;
    type: "0" | "1";
    note?: string | null | undefined;
}

```

**Comment by stijnvanhulle** [comment]
@Jesus-Hernandez23  Can you add the function for `usePostAPIv!Accountants()`. Need to see which types are getting used there causing the `void`.

**Comment by Jesus-Hernandez23** [comment]
> @Jesus-Hernandez23 Can you add the function for `usePostAPIv!Accountants()`. Need to see which types are getting used there causing the `void`.

sure this is generated code: import { useMutation, UseMutationOptions } from '@tanstack/react-query';
import client from '@kubb/swagger-client/client';
import type { PostApiV1AccountantsMutationResponse } from '.\\..\\models\\PostApiV1Accountants';

/**
 * @link /api/v1/Accountants
 */
export function usePostApiV1Accountants<TData = PostApiV1AccountantsMutationResponse, TError = unknown>(options?: {
  mutation?: UseMutationOptions<TData, TError>;
}) {
  const { mutation: mutationOptions } = options ?? {};

  return useMutation<TData, TError>({
    mutationFn: () => {
      return client<TData, TError>({
        method: 'post',
        url: `/api/v1/Accountants`,
      });
    },
    ...mutationOptions,
  });
}

**Comment by stijnvanhulle** [comment]
@Jesus-Hernandez23 This Seems to be an issue related to the paths that are getting generated. Node.js always uses / but for some reason we have a bug that makes use of the `platform` and converts / to \ for Windows.

See `'.\\..\\models\\PostApiV1Accountants';`

Will be fixed with [chore/e2eWindows(](https://github.com/kubb-project/kubb/pull/279) and also added a Github actions for Windows to be 100% sure.

**Comment by Jesus-Hernandez23** [comment]
@stijnvanhulle thanks this fix help me a lot but I still have struggle when performing the type checking in TypeScript because TVariables is always of type void even when it receives parameters.

I checked generated function for usePostAPIv!Accountants() and i realized that the type definition is not being passed to TVariables.
![image](https://github.com/kubb-project/kubb/assets/83924460/32be25df-8fda-4d6e-88b3-5b84042a34ae)
![image](https://github.com/kubb-project/kubb/assets/83924460/c2df9400-47da-47e3-a45a-c3eaf2087fc3)

i can keep fixing this manually but obviously when execute again kubb --config ./kubb.config.ts my changes are going to be deleted or unsynced
![Screenshot 2023-06-11 011319](https://github.com/kubb-project/kubb/assets/83924460/e2e6e167-cdf9-4ef4-a94d-ebea9d046705)

`"post": {
                "tags": [
                    "Accountants"
                ],
                "requestBody": {
                    "content": {
                        "application/json-patch+json; x-api-version=1.0": {
                            "schema": {
                                "$ref": "#/components/schemas/AddAccountant"
                            }
                        },
                        "application/json; x-api-version=1.0": {
                            "schema": {
                                "$ref": "#/components/schemas/AddAccountant"
                            }
                        },
                        "text/json; x-api-version=1.0": {
                            "schema": {
                                "$ref": "#/components/schemas/AddAccountant"
                            }
                        },
                        "application/*+json; x-api-version=1.0": {
                            "schema": {
                                "$ref": "#/components/schemas/AddAccountant"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Success",
                        "content": {
                            "text/plain; x-api-version=1.0": {
                                "schema": {
                                    "$ref": "#/components/schemas/StringApiResponse"
                                }
                            },
                            "application/json; x-api-version=1.0": {
                                "schema": {
                                    "$ref": "#/components/schemas/StringApiResponse"
                                }
                            },
                            "text/json; x-api-version=1.0": {
                                "schema": {
                                    "$ref": "#/components/schemas/StringApiResponse"
                                }
                            }
                        }
                    }
                }`

**Comment by stijnvanhulle** [comment]
Aha found the issue, we had hardcoded to always use `application/json` as requestBodyType but here you are using `application/json; x-api-version=1.0` which was not getting found by our generator.

I will open a PR so it's not hardcoded anymore :)
