### ISSUE TITLE
Specify the base URL for the generated requests

### ISSUE THREAD

**Issue by ekatioz** [kubb-project/kubb#275]
### What is the problem this feature would solve?

If your API Server is on a separate domain or just routed with an URL prefix like `/api/`, there seem to be no way of telling this to the generator. This results in manual editing the generated files to prepend the "baseUrl" before the generated paths.

### What is the feature you are proposing to solve the problem?

At this point, I can think of 2 possible ways to tackle the issue.

- One could use an entry in the kubb config. 
- Another way could be to read the base URL from `severs.url` field in the openapi input file.
- In both ways you can just stick it in front of each generated URL in the `queryFn`.

The config way being more versatile, if the openapi file does not match the current routing (i.e. local development).
Reading the information from the openapi file seems to be more standart-ish (i.e. [@7nohe/openapi-react-query-codegen](https://github.com/7nohe/openapi-react-query-codegen) seems to do it that way).

**Comment by stijnvanhulle** [comment]
Thanks for the feedback. This was indeed something that was missing and also something that is important to have.

So I did the following thing:
- In the config of `@kubb/swagger` you can specify a `serverIndex` to say which server you want to use(with a default of 0). See https://kubb-git-feat-serversurl-kubb.vercel.app/plugins/swagger
- Possibility to set the `baseURL` of an Axios instance. See https://kubb-git-feat-serversurl-kubb.vercel.app/plugins/swagger-client/client. `examples/advanced` has an example of how you can do this with a custom `client.ts` file.


https://github.com/kubb-project/kubb/pull/277
https://kubb-git-feat-serversurl-kubb.vercel.app/

Feel free to add some feedback on how this can be better 😀.

**Comment by ekatioz** [comment]
Thanks for the fast reaction! Looks good to me. I'm going to try it later today.

**Comment by stijnvanhulle** [comment]
@ekatioz You can try this with the following CodeSandbox container: https://codesandbox.io/s/advanced-pet-store-2nw58p

**Comment by ekatioz** [comment]
@stijnvanhulle thank you, I tested it in a vite app using the commit-hash versions for the dependencies. The result looks good, but I wasn"t able to run it, because swagger-ts is generating broken models like:

```
export type Pet = new () => ;
```

But I don"t think this is related to this feature, as i get the same broken models in 1.1.12.

Besides that, I was a bit suprised, that when using the default `@kubb/swagger-client/client.ts`, it tries to use node.js stuff like require and process on the client, what results in "... is not defined" errors.

**Comment by stijnvanhulle** [comment]
@ekatioz For `@kubb/swagger-client/client.ts` just use `@kubb/swagger-client/client`, that will result in the correct file(depending on ESM/CJS).

Can you provide me with your `kubb.config` and Swagger file for that error?

**Comment by ekatioz** [comment]
@stijnvanhulle sure can
```
import { defineConfig } from "@kubb/core";

export default defineConfig(async () => {
  return {
    root: ".",
    input: {
      path: "./petstore.yaml",
    },
    output: {
      path: "./src/gen",
      clean: true,
    },
    logLevel: "info",
    plugins: [
      ["@kubb/swagger", { output: false, validate: true }],
      ["@kubb/swagger-ts"],
      [
        "@kubb/swagger-tanstack-query",
        {
          client: "./src/client.ts",
        },
      ],
      ["@kubb/swagger-client"],
    ],
  };
});
```

```
openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger Petstore
  license:
    name: MIT
servers:
  - url: http://localhost:8080/v1
paths:
  /pets:
    get:
      summary: List all pets
      operationId: listPets
      tags:
        - pets
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            maximum: 100
            format: int32
      responses:
        "200":
          description: A paged array of pets
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pets"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Create a pet
      operationId: createPets
      tags:
        - pets
      responses:
        "201":
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /pets/{petId}:
    get:
      summary: Info for a specific pet
      operationId: showPetById
      tags:
        - pets
      parameters:
        - name: petId
          in: path
          required: true
          description: The id of the pet to retrieve
          schema:
            type: string
      responses:
        "200":
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pet"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Pet:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
    Pets:
      type: array
      maxItems: 100
      items:
        $ref: "#/components/schemas/Pet"
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
```

**Comment by stijnvanhulle** [comment]
hmm can you add me a Sandbox with what you are trying to do, tried this and seems to be working fine on the latest version as also on this PR.

URL with our playground also seems fine: [Playground](https://play.kubb.dev/?version=1.1.13&code=H4sIAAAAAAAAA9VWS2%2FTQBC%2B51eMAgc4tHZahCrfAFUiEqBI9A8s9jje4n10d5w0Qvx3Zu3Y2aRxlYhDVR%2BieF777TcvG4taWJnB9PoyvUynE6lLk00AVui8NDqDWZCzgCTVmMHPtVgu0cECyZNxyJpa5qg9Bi8ALRRbfZ%2FfTTy6ECSIL6BxdQYVkc2SpDa5qCvjKbtJb9JkNZtYQVVrmFgO2wVaInV%2FAHyjlHCbDL5JTyDqGoLZVmksOkEMdV5kDMXTYqcjsfR9kIAicrPCMVLaAuwNOvS1VJIGKYBkGh4adJtIVqDPnbTUcvTVrEEJvQFJqDyQAYfUOA2CwGhk7hTCOyUeYZam76MoDh8a6ZCRl6L2GGl8XqESWSTh62wso5OakDOwp%2BHQUjUqC%2FH3FKVxSlDrdH016Q%2F11nDCoptPr9J0mo1d7xOztcQChHNiA6aMeQxPhaLYIzI8jxcaH2lf9iRuLfXvQBdVCMG8PSicMGA88D9Gy44aT07qZaTMDZOlD1AIa7lk25pJ7j0DOfGMtw5LbpQ3SW4Ug%2BO4PulsfRKKbjp4FFiKpqZRQhu%2Bq8WcmFN0zriXQHwbDu4g29CLh732xaEgBBGSfazV8lZ%2FWrMdr7jZeMX9aLjJe6%2FXSWs7ypI%2F%2FDsv%2Fo6PtDnP29ClTLRn7LKU%2BRjjvjJr5vvzZl7833xrMR3MtzCCjw4mcg2OEX7HbSuL0K%2BhgTnsdvQ5iavThtlex549mG77dPee4XwBK1HLor0CenqJIuAsvcphsNME962yi7TY1W6XOfPrnkEPmduWS1RrsjgovL4yXahqknGaZRHjHdtz0TL7%2BGGQtzX9xPtgFXCnPGuzGL47emW77LYSXq%2FzsNnj%2Fdqu%2Bl3Mk8qhpflMGnNTYPSq0Hvekc9wGRzOZHP4NIA%2B%2FhhZ%2FwDvuoLEMAoAAA%3D%3D&config=H4sIAAAAAAAAA22OwQ6CMBBE%2F2XOhd45%2BQ8eCYcF19pQ29puNYTw74IaEw23nZd5k52RQhA0qKFgfSzrPSOSXDamI8tRQuJ6oqvDohCK%2FHYM%2B41HV4z1GU3b4jCWvtf5QcZwgpq%2F0plcZoU7OXsiYTSSCi%2Bd%2BlMqydiB5LPQMFa3wmnaZgdn2b9%2B1zkN%2Bh3rVd6Z%2FHS7bnkC9EwUwfIAAAA%3D)
