### ISSUE TITLE
Generating clients from a subset of the input file

### ISSUE THREAD

**Issue by la55u** [kubb-project/kubb#344]
### What is the problem this feature would solve?

The problem is that sometimes schemas and paths unrelated to the project are also included in the Swagger file to keep the definitions in the same place for multiple related projects e.g. CMS and frontend. Our current openapi.yml file is over 40k lines long, but only about 1/3 of that is actually needed for the generated frontend client. The generated types and client files are huge which makes the IDE freeze and autocompletion slow and it's generally hard to find which exact function you'd like to use if they're named similarly.

### What is the feature you are proposing to solve the problem?

I propose a config option that would enable to skip certain parts of the input spec file in the generator process. This could be either per tags, schema name, path name etc. It could be a regex which, in our case would allow us to skip many tags since they reflect the controller name on the backend: `PlacesCreateRequestBody` vs `CmsPlacesCreateRequestBody` etc.

### What alternatives have you considered?

Setting the config to generate each type/request into it's own file and then manually deleting the ones that I don't need via a script. (error-prone)

Thanks for your work!

**Comment by stijnvanhulle** [comment]
Based on https://github.com/kubb-project/kubb/pull/350 the following will be possible:

Add a new option `skipBy` to your config where you can define, based on a type, what you want to skip. For now, the types you can skip are `'tag' | 'operationId' | 'path' | 'method' `. The `skipBy` option is an array, which means you can combine multiple skips. `pattern` can be a string or a regExp.

```typescript
import { defineConfig } from '@kubb/core'
import createSwagger from '@kubb/swagger'
import createSwaggerQuery from '@kubb/swagger-tanstack-query'

export default defineConfig({
  root: '.',
  input: {
    path: './petStore.yaml',
  },
  output: {
    path: './src/gen',
    clean: true,
  },
  hooks: {
    done: ['prettier --write "**/*.{ts,tsx}"', 'eslint --fix ./src/gen'],
  },
  logLevel: 'info',
  plugins: [
       createSwagger({ validate: false }), 
       createSwaggerQuery({ 
          output: './clients/hooks',
          skipBy: [
            {
              type: 'tag',
              pattern: 'store',
            },
          ],
          groupBy: { type: 'tag' },
          client: './src/client.ts',
      })
  ],
})

```

Example: https://codesandbox.io/s/advanced-pet-store-xjvrxy?file=/kubb.config.ts

**Comment by la55u** [comment]
That looks amazing, thank you!
One question: is the `skipBy` option only available for the createSwaggerQuery function or all plugins?

**Comment by stijnvanhulle** [comment]
@la55u Yes the idea is that every plugin will have the option `skipBy` so you can decide which parts you need for plugin x.
