### ISSUE TITLE
Custom client import is invalid in the generated files

### ISSUE THREAD

**Issue by la55u** [kubb-project/kubb#361]
### What version of `kubb` is running?

1.5.2

### What platform is your computer?

Fedora Linux

### What steps can reproduce the bug?

Repro: https://github.com/la55u/kubb-client-import-bug

1. clone the repo
2. run `npm i && npm run generate`
3. inspect the wrong import in `src/gen/requests.ts`

### What is the expected behavior?

The import statement at the top of requests.ts should be `import client from '../client'`. Currently it is `import client from './client'` which points to a non-existing file.
OR it should use the client that is copy-pasted into the bottom in `requests.ts` without importing to avoid duplicating the axios instance.

### Swagger/OpenAPI file?

[default petstore](https://raw.githubusercontent.com/kubb-project/kubb/main/examples/typescript/petStore.yaml)

### Additional information

This config used to work in previous versions, not sure when it was changed.

Thank you for your help!

**Comment by stijnvanhulle** [comment]
@la55u The bug should be fixed with version `1.5.3`
