### ISSUE TITLE
Possibly incorrect Zod schema generation when using `allOf` and non-object types

### ISSUE THREAD

**Issue by absolutejam** [kubb-project/kubb#362]
### What version of `kubb` is running?

1.5.2

### What platform is your computer?

Linux

### What steps can reproduce the bug?

I've created a minimal reproduction here: https://github.com/absolutejam/kubb-minimal-repro

If I try to run `pnpm ts-node ./index.ts`, it will fail with a Zod error that says  `Expected object, received string`. This is because the generated type is an intersection of an object and string.

```ts
z.ZodIntersection<z.ZodObject<{}, "strip", z.ZodTypeAny, {}, {}>, z.ZodLazy<z.ZodString>>>>
```

I think this could also be chalked up to my backend framework generating the type as an `allOf` in the schema (this is because it's coming from an `Option<String>` in Rust) but I came here first because it seemed more of a Zod error than a schema error, and as it is essentially generating a Zod schema for a type that can't be constructed without bypassing the type system. 

As well as this, when I check the generated models (`gen/model/CreateTestRequest.ts`) I see that it generates what I would expect:

```ts
export type CreateTestRequest = {
    content?: (TestContent) | undefined;
    name: TestName;
};
```

I did also review the OpenAPI docs to understand how `allOf` should be handled, but they just describe the usage of `allOf` as a means of merging 'object definitions'. In OpenAPI terms, I'm not sure if an 'object' means the same as the JS version (ie. `{}`) or if it means a 'type', and looking at the `TestContent` schema object, it does define `"type": "string"` so perhaps the `allOf` here should be flattened at the Zod level?

---

Just FYI, if I remove the `allOf` manually in my schema, the resulting Zod schema is what I expected.

From:

```
          "content": {
            "allOf": [
              {
                "$ref": "#/components/schemas/TestContent"
              }
            ],
            "nullable": true
          },
```

to:

```json
          "content": {
            "$ref": "#/components/schemas/TestContent"
            "nullable": true
          },
```

Generates:

```ts
export const createTestRequestSchema = z.object({
  "content": z.lazy(() => testContentSchema).nullish(),
  "name": z.lazy(() => testNameSchema),
});
```

instead of:

```ts
export const createTestRequestSchema = z.object({
  "content": z.object({}).and(z.lazy(() => testContentSchema)).nullish(),
  "name": z.lazy(() => testNameSchema),
});
```

And now `pnpm ts-node index.ts` does not fail with a Zod error.

### What is the expected behavior?

The `createTestRequestSchema.content` should generate a `string` field, not an `object & string` field.

### Swagger/OpenAPI file?

In the attached repo as `schema.json`

**Comment by stijnvanhulle** [comment]
@absolutejam This will be fixed with version `1.5.4`(https://github.com/kubb-project/kubb/pull/365)
