### ISSUE TITLE
Nullable fields loses their type (swagger-ts)

### ISSUE THREAD

**Issue by TormodNy** [kubb-project/kubb#380]
### What version of `kubb` is running?

kubb/1.6.0 linux-x64 node-v16.20.0

### What platform is your computer?

Windows running WSL2

### What steps can reproduce the bug?

I have an OpenAPI 3.1 schema with nullable fields. When I generate the models with `createSwaggerTS` their types are lost and are replaced with `any` instead.

This schema
```json
"bar": {
    "anyOf": [
        {
            "type": "string"
        },
        {
            "type": "null"
        }
    ],
    "title": "Bar"
}
```
gives
```ts
bar?: any | undefined;
```

And this schema
```json
"schema": {
  "type": "array",
  "items": {
      "type": "array",
      "items": {
          "anyOf": [
              {
                  "type": "number"
              },
              {
                  "type": "null"
              }
          ]
      },
      "minItems": 2,
      "maxItems": 2
  },
  "title": "Foos"
}
```
gives
```ts
foos: any[][];
```

### What is the expected behavior?

I expect the types to be something like this:

```ts
bar?: string | null;

foos: (number | null)[][];
```

**Comment by stijnvanhulle** [comment]
I opened a PR to fix this, the behaviour of `anyOf` will become the same as `oneOf`. This will result in the correct type being generated by the swagger-ts plugin 😀.
