### ISSUE TITLE
(Feature Request):  Ability to override Date types to be Javascript Dates

### ISSUE THREAD

**Issue by jafin** [kubb-project/kubb#385]
### What is the problem this feature would solve?

Currently, a schema that has a field defined as

```yml
 effectiveDate:
    type: string
    format: date-time
```
will create a model of type string. It would be useful if there was a way to override this to use a Javascript `Date` instead.  
It would be up to the user to ensure they have a data reviver or similar to perform the necessary conversion. This request is just to allow the model to have the type of `Date` 

```ts
  /**
   * @type string | undefined date-time
   */
    effectiveDate?: string | undefined;
```

Similar : https://github.com/anymaniax/orval/blob/6439bbdab903117d4420bdca9b05658f246df9d1/docs/src/pages/reference/configuration/output.md?plain=1#L990

### What is the feature you are proposing to solve the problem?

Option to override type string, format:date-time to use native JS Date via config. 

### What alternatives have you considered?

at present, creating a new type that overrides the emitted type, and update the field.
Such that I don't have to touch generated code, but downside being new types have to be used and maintained.

```ts
type Override<T1, T2> = Omit<T1, keyof T2> & T2;
type NewModel = Override<Model, { effectiveDate: Date | undefined }>;
```

**Comment by stijnvanhulle** [comment]
@jafin Version `1.7.0` of Kubb will contain a new option that you can set to change between `string` and `Date`. The same option has also been added to the Faker plugin.

Updated docs: https://kubb-git-385-feature-request-ability-to-override-da-2c80a5-kubb.vercel.app/plugins/swagger-ts#datetype
