### ISSUE TITLE
>`v1.8.1` breaks generation for `PATCH` methods

### ISSUE THREAD

**Issue by NimmLor** [kubb-project/kubb#416]
### What version of `kubb` is running?

kubb/1.8.3 win32-x64 node-v18.15.0

### What platform is your computer?

Windows 11

### What steps can reproduce the bug?

1. Use any OpenAPI with a PATCH method
2. Install kubb 1.8.1, 1.8.2 or 1.8.3

v1.8.1 seems to break the zodius output completely and v1.8.2/3 generate output without patch methods.

### What is the expected behavior?

Generation of PATCH methods as in v1.8.0

**Comment by stijnvanhulle** [comment]
@NimmLor Will fix this asap! :)

**Comment by NimmLor** [comment]
> @NimmLor Will fix this asap! :)

thanks 👍🏻

**Comment by stijnvanhulle** [comment]
@NimmLor 1.8.4 should fix this, feel free to reach out for other bugs related to this :)
