### ISSUE TITLE
MSW/Faker plugins generate files with unused imports

### ISSUE THREAD

**Issue by antipopp** [kubb-project/kubb#442]
### What version of `kubb` is running?

kubb/1.5.4 linux-x64 node-v20.7.0

### What platform is your computer?

Linux

### What steps can reproduce the bug?

Run this [example](https://www.kubb.dev/examples/msw). You'll notice that all the generated handlers that have a request payload by spec (e.g. the `add` or `update` handlers) will have a `{{something}}Request` import that will go unused. 

This clashes with one of the most common and recommended rule by ESLint `no-unused-vars`, which is not fixable with `eslint --fix`.

This also happens with generated mocks with the faker plugin. In `gen/mocks/petMocks/createUpdatePet.ts` you'll find an unused faker import.

### What is the expected behavior?

Unnecessary imports should be avoided.

**Comment by stijnvanhulle** [comment]
The request import was an issue and has been removed. The `faker` import needs a rewrite of our imports logic(not all generated codes need them). In the meantime you can use the following for eslint: https://stackoverflow.com/questions/64365300/how-can-i-remove-unused-imports-declarations-from-the-entire-project-of-react-ty
