### ISSUE TITLE
swagger-swr plugin doesn't support Conditional Fetching.

### ISSUE THREAD

**Issue by b6pzeusbc54tvhw5jgpyw8pwz2x6gs** [kubb-project/kubb#447]
### What is the problem this feature would solve?

[swr](https://swr.vercel.app) can conditional patching by passing the first argument as `null` when calling `useSWR()', as shown in the documentation at https://swr.vercel.app/docs/conditional-fetching. This is a very useful feature that allows you to delay making an API request until the API request arguments are fetched asynchronously. However, this feature is not available using the swagger-swr plugin, which is inconvenient.

### What is the feature you are proposing to solve the problem?

I've made a modification that implements conditional patching by passing `null` as the first argument to the useSWR call when this value is `false`, given the option `shouldFetch`.

https://github.com/b6pzeusbc54tvhw5jgpyw8pwz2x6gs/kubb/commit/10f7f5d6ef5e9d84d16569162bf170c787770b99

I'll raise a PR if this direction is okay.

**Comment by stijnvanhulle** [comment]
@b6pzeusbc54tvhw5jgpyw8pwz2x6gs Feel free to open a PR :)
