### ISSUE TITLE
support for `ref`s in tanstack query for vue 

### ISSUE THREAD

**Issue by WickyNilliams** [kubb-project/kubb#449]
### What is the problem this feature would solve?

right now, the generated composables/hooks for tanstack query vue only accept plain/unreactive values. tanstack query's vue wrapper expects reactive values to be passed as the query key so that it can track and respond to updates over time. 

this is due to the fact that vue's setup function is only executed once. so unlike react, the hooks/composables only receive one invocation. thus you have to use reactive values to invoke changes

without this, a query cannot fetch with updated paramters, limiting the utility of the generated composables. 

an example would be:

```vue
<script setup>
const id = ref(0)
const user = useUser(id)
</script>

<template>
  <template v-if="user.isSuccess">
    <pre>
      {{ JSON.stringify(user.data, null, 2) }}
    </pre>
    
    <button @click="id++">Next</button>
  </template>
</template>
```

### What is the feature you are proposing to solve the problem?

i am proposing that the output signature for vue composables should accept all types of params as `MaybeRef<T>`. these values get passed to the queryKey function untouched, but get `unref`d when passed to API as path/query params etc. essentially the signature should be something like this:

```ts
function useSomething(
  somePathParam: MaybeRef<string>,
  params: {
    pageNumber: MaybeRef<number>,
    filter: MaybeRef<string>
  }
) {
  // ...
}
```

not sure if you'd also need to wrap the `params` object in `MaybeRef` also, to make it as flexible as possible - sometimes you want to pass an object of refs, sometimes you want to pass a ref object. 

```ts
const pageNumber = ref(0)
const filter = ref("")

// object of refs
const query = useSomeQuery({
  pageNumber,
  filter
})

// ref object
const params = ref({
  pageNumber: 0,
  filter: ""
})
const query = useSomequery(params)
```

maybe you could use function overloading to separate these use cases

### What alternatives have you considered?

the alternative would be imperatively calling `refetch` or something, which is definitely not the intended way to use tanstack query!

**Comment by stijnvanhulle** [comment]
@WickyNilliams Thanks for the explanation and for using Kubb 👍🏼 .

I have been trying to add `MaybeRef` and `unRef` and the types seem to work fine now. 
But I'm having an issue making it work when clicking on for example a button(switching between `status`).

Any clue what I'm missing here to make an update work between the `ref` and `vue-query`?

Codesandbox: https://codesandbox.io/s/vue-query-pet-store-h7mcqj
PR: https://github.com/kubb-project/kubb/pull/461

`App.vue`
```
<script lang="ts">
import { defineComponent, ref } from 'vue';
import { FindPetsByStatusQueryParamsStatus } from './index.ts';
import Pets from "./Pets.vue"

export default defineComponent({
  name: 'App',
  components: { Pets },
  setup() {
    const status = ref<FindPetsByStatusQueryParamsStatus>("available")

    return {
      status,
      setStatus(newStatus:FindPetsByStatusQueryParamsStatus ){
        status.value= newStatus
      }
    };
  },
});
</script>

<template>
  <Pets :status="status" @setStatus="setStatus" />
</template>

```

`Pets.vue`
```
<script lang="ts">
import { defineComponent, computed, unref } from 'vue';
import { useFindPetsByStatus, FindPetsByStatusQueryParams } from './index.ts';

export default defineComponent({
  name: 'PetsList',
  emits: ['setStatus'],
  props: {
    status: {
      type: String,
      required: true,
    },
  },
  setup(props) {
    const params = computed(() =>{
      return {
        status: props.status as FindPetsByStatusQueryParams["status"]
      }
    })
    
    const petsQuery = useFindPetsByStatus(params  )

    const pets = computed(() => unref(petsQuery?.data));

    return {
      pets
    };
  },
});
</script>

<template>
  <div class="pets" v-if="pets">
    <h1>Pets: {{ status }}</h1>
    <ul v-for="pet in pets" :key="pet.id">
      <li :key="pet.id">{{pet.name}}</li>
    </ul>
  </div>
  <button @click="$emit('setStatus', 'available')" >Available</button>
  <button @click="$emit('setStatus', 'pending')" >Pending</button>
</template>
```

**Comment by WickyNilliams** [comment]
No worries! 

I believe where you've gone wrong is calling `unref` on params passed to the query key fn. Tanstack query for vue expects refs/reactive values as part of query keys, so it can subscribe to them and refetch on change. Hard to give a better answer as I'm on mobile atm. But I can take a proper look tomorrow, if you're still flummoxed by then!

**Comment by stijnvanhulle** [comment]
@WickyNilliams Thanks a lot, I also updated the PR (queryKey without `unref`) and it's working now 🎉. 
Just need to test some edge cases to see if all `refs` are working correctly :)

**Comment by stijnvanhulle** [comment]
@WickyNilliams Merged the PR(see https://github.com/kubb-project/kubb/pull/461), you can start using it with the `canary` flag. 

https://www.kubb.dev/introduction#installation
<img width="716" alt="Screenshot 2023-10-09 at 1 24 50 PM" src="https://github.com/kubb-project/kubb/assets/5904681/aa7e666c-0038-4637-829d-11e3895c9e2b">

**Comment by WickyNilliams** [comment]
Awesome, i'll give it a go and see how i get on! Thanks for the quick turnaround.
