### ISSUE TITLE
Incorrect response type `Promise<any>` on the generated axios requests

### ISSUE THREAD

**Issue by la55u** [kubb-project/kubb#456]
### What version of `kubb` is running?

1.9.5

### What platform is your computer?

Fedora Linux

### What steps can reproduce the bug?

Minimal reproduction here: https://github.com/la55u/kubb-ts-bug

See main.ts file and hover over `res`, it it showing the type as `Promise<any>`

### What is the expected behavior?

Variable `res` should be of type `Promise<UserProfileResponse>`. 

### Swagger/OpenAPI file?

https://github.com/la55u/kubb-ts-bug/blob/dev/openapi.yaml

### Additional information

This used to work in previous versions of kubb. 
Also, in models.ts file there is an `any | null` type that's probably causing the issue?

Thank you, love using kubb <3

**Comment by stijnvanhulle** [comment]
@la55u Seems that we had a check on `200` for all responses and because yours is using `201` we were ignoring that one. opening a PR to fix this :).
