### ISSUE TITLE
`@kubb/swagger@1.11.0` depends on `@kubb/react`

### ISSUE THREAD

**Issue by NimmLor** [kubb-project/kubb#478]
### What is the issue?

Hi, `@kubb/swagger@1.11.0` now requires `@kubb/react` as peerDep. Is this really neccessary? For what I can see, it's only used to re-export `useSchemas`, `useOperation` and `useResolve`. 

I propose that it should be removed or documented.

### Where did you find it?

@kubb/swagger/dist/index.cjs

**Comment by stijnvanhulle** [comment]
Are you having issues with building/generating(it should be installed automatically)?

`@kubb/react` is a experimental package(only internal being used). I will first see if it can do the trick and then update the docs for https://www.kubb.dev/plugins/react.

**Comment by NimmLor** [comment]
Yarn does not install `peerDependencies` automatically (in constrast to npm > v7), it just prints out a warning.

(see https://docs.npmjs.com/cli/v8/configuring-npm/package-json#peerdependencies)

Running kubb without `@kubb/react` leads to the following crash:

```
 ✖ Cannot find module '@kubb/react'
Require stack:
- C:\xxxx\xxxx-xxxx\node_modules\@kubb\swagger\dist\index.cjs
- C:\xxxx\xxxx-xxxx\packages\openapi\kubb.config.ts
- C:\xxxx\xxxx-xxxx\node_modules\@kubb\cli\dist\index.js
  Error: Cannot find module '@kubb/react'
  Require stack:
  - C:\xxxx\xxxx-xxxx\node_modules\@kubb\swagger\dist\index.cjs
  - C:\xxxx\xxxx-xxxx\packages\openapi\kubb.config.ts
  - C:\xxxx\xxxx-xxxx\node_modules\@kubb\cli\dist\index.js
```
