### ISSUE TITLE
Allow overriding infinite query `pageParam` on individual functions/hooks

### ISSUE THREAD

**Issue by joaomlneto** [kubb-project/kubb#482]
### What is the problem this feature would solve?

One of the schemas I'm working with has endpoints that may use either regular offset pagination or cursor-based pagination, and have their pagination parameters named differently.

I need a way to generate Infinite queries using different `pageParam` names.

```js
{
  page: 1, // return page number 1, 2, 3, …
  // or
  last_record_id: 123, // return N records after/before ID 123, 456, 789, …
}
```

### What is the feature you are proposing to solve the problem?

Let Kubb allow us to specify the Infinite Query parameter name on a per-endpoint basis.

My suggestion is to have the option to override the `pageParam` on the hook/client:
```ts
useXXXInfinite(…, {query: {pageParam: "myNewPageParam", …}, …})
```

### What alternatives have you considered?

1. Run Kubb multiple times separately to generate the methods with different `pageParam` names. This causes unnecessary complex configuration and longer compile times.
2. Override the `queryFn`: may break things in the long run, and is also harder to use.

**Comment by stijnvanhulle** [comment]
Hi, I'm thinking about adding the following(`overrideBy`):

```

createSwaggerTanstackQuery({
      output: './clients/hooks',
      skipBy: [
        {
          type: 'tag',
          pattern: 'store',
        },
      ],
      groupBy: { type: 'tag' },
      client: './src/client.ts',
      infinite: { 
         queryParam: "page" // default
      },
     overrideBy: [
        {
          type: "tag",
          pattern: 'store',
          options: {
            infinite: { 
              queryParam: "last_record_id" // when a tag is equal to store it will use last_record_id instead of page
            },
          }
        }
     ]
    }),
```

**Comment by stijnvanhulle** [comment]
@joaomlneto An example: https://github.com/kubb-project/kubb/pull/511/files
