### ISSUE TITLE
Allow using string for input in config

### ISSUE THREAD

**Issue by essential-randomness** [kubb-project/kubb#502]
### What is the problem this feature would solve?

Currently, the only configuration option to pass open API data to generate from is to use `path`. This require that the data be written to the filesystem before using the library. 

In my case, the OpenAPI configuration is exported by an external library, which means I need to write it to a file before using kubb. It would be nice to be able to pass a string (or object) directly. 

### What is the feature you are proposing to solve the problem?

Something like:

```ts
import openApiSpec from "@bobaboard/boba-backend-open-api";

export default defineConfig(async () => {
  return {
    input: {
      data: openApiSpec,
    },
  };
});
```

Here `data` could be an object or a string representing a YAML or JSON open API config.

### What alternatives have you considered?

Importing the spec, writing it to the filesystem, then generating the types. I'd rather not do that, but it's not infeasible.

Thank you!

**Comment by stijnvanhulle** [comment]
You can try this out with our canary build: https://www.kubb.dev/introduction#installation
`pnpm add @kubb/cli@canary @kubb/core@canary`
