### ISSUE TITLE
improve query keys in tanstack query plugin

### ISSUE THREAD

**Issue by WickyNilliams** [kubb-project/kubb#513]
### What is the problem this feature would solve?

looking at how the query keys are sturctured for tanstack query (vue here, but i assume its the case for react too):

```ts
export const retrieveUserQueryKey = (
  id: MaybeRef<RetrieveUserPathParams["id"]>,
  params?: MaybeRef<RetrieveUserQueryParams>,
) =>
  [
    {
      url: `/users/${unref(id)}`,
      params: { id: id },
    },
    ...(params ? [params] : []),
  ] as const;
```

i think it is redundant to interpolate the `id` into the url, since it already forms part of the key via `params.id`. 

additionally, interpolating params into the url makes it difficult/impossible to invalidate all cached queries for the `/users/:id` endpoint (because there is no part of the key that is shared among all queries to the same endpoint)

### What is the feature you are proposing to solve the problem?

i would propose the url not be interpolated:

```ts
export const retrieveUserQueryKey = (
  id: MaybeRef<RetrieveUserPathParams["id"]>,
  params?: MaybeRef<RetrieveUserQueryParams>,
) =>
  [
    {
      url: `/users/:id`,
      params: { id: id },
    },
    ...(params ? [params] : []),
  ] as const;
```

to make it easier to clear the cache:

```ts
queryClient.invalidateQueries({ queryKey: [{ url: "/users/:id" }] })
```

alternatively you could use the `operationId` instead of url 

there's probably quite some scope to further improve query keys e.g. include tags, so that you can invalidate all `User` related queries (both lists and details)

**Comment by WickyNilliams** [comment]
one thought on the keys might be to structure them like:

```ts
[{
  tag: "User"
  operationId: "retrieveUser",
  params: { id: id },
  query: params
}]
```

that way you can:

```ts
// invalidate all User-related cache entries
queryClient.invalidateQueries({ queryKey: [{ tag: "User" }] })

// invalidate all users details
queryClient.invalidateQueries({ queryKey: [{ tag: "User", operationId: "retrieveUser" }] }

// invalidate specific user
queryClient.invalidateQueries({ 
  queryKey: [{ 
    tag: "User", 
    operationId: "retrieveUser",
    params: { id: "1" } 
  }]
})
```

personally i like just using a tuple rather than objects:

```ts
queryClient.invalidateQueries({ queryKey: ["User"] })
queryClient.invalidateQueries({ queryKey: ["User", "retrieveUser"] }
queryClient.invalidateQueries({ queryKey: ["User", "retrieveUser", { id }]
```

but admittedly it is less clear

**Comment by xming13** [comment]
@WickyNilliams 
May I know if it is possible to customise / configure / override the latest version (v2.23.2) to achieve the structure (either tuple or object) as you have suggested?

```
[{
  tag: "User"
  operationId: "retrieveUser",
  params: { id: id },
  query: params
}]
```

Aside, I also noticed in the queryKey function, the type of keys is string instead of object, which makes it hard to implement our own logic.
```
pluginTanstackQuery({
  query: { 
    queryKey: (keys) => {
      console.log('keys:', keys);  // keys: [ '{ url: \'/profiles/me\' }' ]
      const firstKey = keys[0];
      console.log('firstKey:', firstKey, typeof firstKey); // type is string and JSON.parse throw `JSON Parse error: Expected '}'`
    }
  }
})
```

**Comment by WickyNilliams** [comment]
Not sure sorry! I'm no longer working on the project where I was investigating this. So I haven't been keeping up with kubb
