### ISSUE TITLE
Tanstack-query v5: TS error on `return queryOptions()`

### ISSUE THREAD

**Issue by la55u** [kubb-project/kubb#530]
### What version of `kubb` is running?

1.14.2

### What platform is your computer?

Fedora Linux

### What steps can reproduce the bug?

Repro: https://github.com/la55u/kubb-ts-bug

1. run `npm i && npm run generate`
2. open `hooks.ts`
3. the error is in the return statement of `getDailyPromotedPlaceQueryOptions`

### What is the expected behavior?

No error on types

### Swagger/OpenAPI file?

https://github.com/la55u/kubb-ts-bug/blob/dev/openapi.yaml

**Comment by stijnvanhulle** [comment]
Seems that `queryOptions` is converting to DataTag with `queryKey: DataTag<TQueryKey, TData>` not sure why the readonly(with as const) has issues with it but for now I will add a cast to make the TypeScript engine happy ;)

https://github.com/TanStack/query/blob/main/packages/react-query/src/queryOptions.ts

**Comment by la55u** [comment]
Sorry to bother again but I noticed another type issue.
When you want to pass options to the generated react query custom hook, for example `enabled`, TS yells about the missing `queryKey` even though it's specified in the hook itself.
![image](https://github.com/kubb-project/kubb/assets/30611343/b0074889-c5d1-4799-86d8-b4e43a4e0276)

Thank you for your help

**Comment by stijnvanhulle** [comment]
@la55u 

Seems that some types between `solid`, `vue`, `svelte` and `react` are not always the same between v4 and v5 so this will take some extra time to get the types for v5 correct. 

I will keep you up to date 👍🏼

**Comment by stijnvanhulle** [comment]
@la55u  You can try out with our alpha tag
 https://www.kubb.dev/installation#alpha

**Comment by la55u** [comment]
@stijnvanhulle 
Thanks for the heads-up. The issue with `enabled` above is now solved in 2.0.0-alpha.1 but another one did appear with the mutation types. Basically when you do this the first argument in the mutation is of type `never` which is incorrect:
![image](https://github.com/kubb-project/kubb/assets/30611343/0b95ce80-a172-41d8-9907-8e413568b2a9)
Do you want me to open a detailed issue for it or no since it's still alpha? Thanks

**Comment by stijnvanhulle** [comment]
@la55u New version: [2.0.0-alpha.2](https://www.npmjs.com/package/@kubb/core/v/2.0.0-alpha.2) has been released with a fix for the mutations.
