### ISSUE TITLE
how to run the demo react-query; I get a error;   Error: prev.findLast is not a function

### ISSUE THREAD

**Issue by D2cGen** [kubb-project/kubb#547]
### What is the type of issue?

I get a error
```bash
✔ 💾 Config loaded(kubb.config.js)
⚠ fetch is not defined
⚠ fetch is not defined
⚠ fetch is not defined
⚠ fetch is not defined
✖ Something went wrong

  Error: prev.findLast is not a function

```

### What is the issue?

```
copy react-query ~/react-query 
cd ~/react-query 
npm install @kubb/cli @kubb/core @kubb/swagger @kubb/swagger-client @kubb/swagger-tanstack-query @kubb/swagger-ts
npm install @kubb/cli@1.14.3 -g
kubb generate
```

package.json

```json
"dependencies": {
    "@kubb/cli": "^1.14.3",
    "@kubb/core": "^1.14.3",
    "@kubb/swagger": "^1.14.3",
    "@kubb/swagger-client": "^1.14.3",
    "@kubb/swagger-tanstack-query": "^1.14.3",
    "@kubb/swagger-ts": "^1.14.3",
    "@tanstack/react-query": "^4.36.1",
    "@tanstack/react-query-devtools": "^4.36.1",
    "axios": "^1.5.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "tsup": "^7.2.0"
  },


```

**Comment by stijnvanhulle** [comment]
@D2cGen What is your `node` version?

**Comment by D2cGen** [comment]
> @D2cGen What is your `node` version?

node -v
v16.19.0


npm -v
8.19.3

const name = curr.name;
  //  prev, curr = { path: './****' },  miss name

**Comment by stijnvanhulle** [comment]
@D2cGen Can you try with `node 18`? 

We don't support `node 16` anymore because of https://nodejs.org/en/blog/announcements/nodejs16-eol.

**Comment by D2cGen** [comment]
> @D2cGen Can you try with `node 18`?
> 
> We don't support `node 16` anymore because of https://nodejs.org/en/blog/announcements/nodejs16-eol.
> 
> See https://www.kubb.dev/installation

node -v
v18.18.2

i try with node 18, it work fine.  thank you very much💐
