### ISSUE TITLE
`@kubb/swagger-ts`: grouping by tag can result in ambiguous import paths in barrel files

### ISSUE THREAD

**Issue by WickyNilliams** [kubb-project/kubb#552]
### What version of `kubb` is running?

kubb/1.14.3 darwin-arm64 node-v18.15.0

### What platform is your computer?

MacOS

### What steps can reproduce the bug?

take the petstore.yaml, configure `@kubb/swagger-ts` like this:

```ts
createSwaggerTS({
  output: 'types',
  groupBy: { type: 'tag', output: 'types/{{tag}}' },
})
```

this will generate the following dir structure:

```sh
> tree types

/types
├── Error.ts
├── Pet.ts
├── Pets.ts
├── index.ts
└── pets
    ├── CreatePets.ts
    ├── ListPets.ts
    ├── ShowPetById.ts
    └── index.ts
```

the file `types/index.ts`  will look like this:

```ts
export * from "./Error";
export * from "./Pet";
export * from "./Pets"; // a file
export * from "./pets"; // a barrel import/export
```

we have two imports which can't be distinguished on case-sensitive file systems - one for a file and one for a directory (which is relying on tooling resolving the `./pets` -> `./pets/index.ts`)

### How often does this bug happen?

Every time

### What is the expected behavior?

i would expect the generated code to be valid. the files on disk all exist, so it's not a clash at the file system level.

one approach to solve it is not rely on node style `index.js` resolution, and be explicit about both index files and file extensions:

```ts
export * from "./Error.js";
export * from "./Pet.js";
export * from "./Pets.js";
export * from "./pets/index.js";
```

this is unambiguous and will work with all tooling. i don't think it's a given that all tooling will support node-style resolution, so being explicit is probably preferable anyway, outside of the issue. 

it may also be worth adding an option to disable barrel modules, especially since they can lead to performance problems (and/or larger than necessary bundles) https://marvinh.dev/blog/speeding-up-javascript-ecosystem-part-7/

### Swagger/OpenAPI file?

```yaml
openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger Petstore
  license:
    name: MIT
servers:
  - url: http://petstore.swagger.io/v1
paths:
  /pets:
    get:
      summary: List all pets
      operationId: listPets
      tags:
        - pets
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            maximum: 100
            format: int32
      responses:
        '200':
          description: A paged array of pets
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pets"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Create a pet
      operationId: createPets
      tags:
        - pets
      responses:
        '201':
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /pets/{petId}:
    get:
      summary: Info for a specific pet
      operationId: showPetById
      tags:
        - pets
      parameters:
        - name: petId
          in: path
          required: true
          description: The id of the pet to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pet"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Pet:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
    Pets:
      type: array
      maxItems: 100
      items:
        $ref: "#/components/schemas/Pet"
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
```

**Comment by stijnvanhulle** [comment]
@WickyNilliams  In v2 it will be changed to use `/index` by default and that will probably already resolve some issues you had here. For example https://github.com/kubb-project/kubb/blob/alpha/examples/advanced/src/gen/index.ts.

Normally there is no need to add `.js` or `.ts` to the files to use the node-style. If needed `tsc` or other bundlers can resolve that.

Another thing that can also be done is to add all exports instead of using * but that will require some rework.

**Comment by WickyNilliams** [comment]
Cool, yeah, being explicit about index would solve some/most of the issues I believe. 

Personally I always add extensions to imports. The typescript docs all use this style, plus it is required for native esm in the browser. I believe the extensionless form has a cost for module resolution in node and others (since you can't resolve import without first inspecting the FS). Interestingly Ryan Dahl, node's creator, lists both index and extensionless resolution as design mistakes in node https://tinyclouds.org/jsconf2018.pdf

But that is a matter of preference :)

**Comment by stijnvanhulle** [comment]
v2 will contain an option to set the `extName`
```typescript
output: {
  path: 'models/ts',
  extName: '.js',
},
```

**Comment by chiptus** [comment]
@stijnvanhulle will v2 include an option to disable barrel exports?

**Comment by stijnvanhulle** [comment]
@chiptus https://beta.kubb.dev/plugins/swagger-client/#output-exporttype
