### ISSUE TITLE
More strict type for swagger-client, swagger-swr

### ISSUE THREAD

**Issue by b6pzeusbc54tvhw5jgpyw8pwz2x6gs** [kubb-project/kubb#582]
### What is the problem this feature would solve?

When I use the code that swagger-client generates, it's not strictly type-checked.

For example, suppose this is the code you generated,

```ts
import client from "@lib/myData-client";
import type { ResponseConfig } from "@lib/myData-client";
import type { CreateMyDataPostMutationRequest, CreateMyDataPostMutationResponse } from "./models/ts/CreateMyDataPost";

export async function createMyDataPost <
  TData = CreateMyDataPostMutationResponse,
  TVariables = CreateMyDataPostMutationRequest
>(
  data: TVariables,
  options: Partial<Parameters<typeof client>[0]> = {}
): Promise<ResponseConfig<TData>["data"]> {
    const { data: resData } = await client<TData, TVariables>({
        method: "post",
        url: `/api/myData`,
        data,
        ...options
    });

    return resData;
};
```

If you use this like below, you won't get an error. This is because the code uses generic types and is not strictly type-checked.

```ts
  createMyDataPost({ wrong: 'value'  })
```

Replace the above code with the following to make it strictly type-checked.

```ts
export async function createMyDataPost (
  data: CreateMyDataPostMutationRequest,
  options: Partial<Parameters<typeof client>[0]> = {}
): Promise<ResponseConfig<CreateMyDataPostMutationResponse>["data"]> {
    const { data: resData } = await client<CreateMyDataPostMutationResponse, CreateMyDataPostMutationRequest>({
        method: "post",
        url: `/api/myData`,
        data,
        ...options
    });

    return resData;
};
```

How about adding an option like "strict-type-check: boolean" as a plugin option to generate something like the second code? I'll raise the PR if that's okay.

**Comment by stijnvanhulle** [comment]
@b6pzeusbc54tvhw5jgpyw8pwz2x6gs It makes more sense to me that code example 2 will be the only generated code. Generics here are not needed because we already know the schema and types. I will adapt/change this with version 2 of Kubb.

Extra type for the ts plugin(TODO):
```
type CreateMyDataPostMutation = {
   request: CreateMyDataPostMutationRequest
   response: CreateMyDataPostMutationResponse
}
```

**Comment by b6pzeusbc54tvhw5jgpyw8pwz2x6gs** [comment]
@stijnvanhulle I'm applying kubb to my project. I don't have much time to wait for v2, so can I create PR applying this part to v1 right away?

**Comment by stijnvanhulle** [comment]
@b6pzeusbc54tvhw5jgpyw8pwz2x6gs Jeah sure go ahead, you can probably copy paste some stuff of the alpha branch for this :)
