### ISSUE TITLE
Dependence on cosmiconfig for @kubb/cli throws breaking error in es module envrionments

### ISSUE THREAD

**Issue by madi-tracksuit** [kubb-project/kubb#599]
### What version of `kubb` is running?

kubb/1.14.6 darwin-arm64 node-v18.16.0

### What platform is your computer?

MacOS

### What version of external packages are you using(`@tanstack-query`, `MSW`, `React`, `Vue`, ...)

``` 
"@kubb/cli": "^1.14.6", 
"@kubb/swagger": "^1.14.6",
"@kubb/swagger-client": "^1.14.6",
"@kubb/swagger-faker": "^1.14.6",
"@kubb/swagger-ts": "^1.14.6",
"@kubb/swagger-zod": "^1.14.6",
```

### What steps can reproduce the bug?

The `@kubb/cli` relies on `cosmicconfig` to resolve config files, cosmic config doesn't yet support es modules (afaik), so you get the `[ERR_REQUIRE_ESM]: require() of ES Module not supported` error when it tries to `require` your config.

Steps to repro:

- Create a `kubb.config.js` file in a project with `type: module` defined in `package.json`
- Try and run `kubb`
- See error

### How often does this bug happen?

Every time

### What is the expected behavior?

Kubb CLI should be able to run in es modules

**Comment by stijnvanhulle** [comment]
Maybe this could help you out: https://www.kubb.dev/configuration/configure#typescript-javascript.

If `type: module` is being used you need to use an `import` syntax, you can rename the file to `kubb.config.cjs` and that should then use CJS instead.

**Comment by madi-tracksuit** [comment]
@stijnvanhulle I am using es imports everywhere, but cosmic uses `require` when loading the config file, so if it uses es import/export syntax (like the docs suggest) it throws

**Comment by stijnvanhulle** [comment]
@madi-tracksuit Tried it with the following codesandbox but seems to work fine here, can you provide me a codesandbox/fork with the issue?

[codesandbox example](https://codesandbox.io/p/sandbox/msw-pet-store-forked-xj5wz9?file=%2Fpackage.json%3A17%2C38&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clooup2gm00072e6gb0cw3thr%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clooup2gm00032e6gin7fkzt6%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clooup2gm00052e6gdxqbxliy%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clooup2gm00062e6gpm7des8q%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B60%252C40%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clooup2gm00032e6gin7fkzt6%2522%253A%257B%2522id%2522%253A%2522clooup2gm00032e6gin7fkzt6%2522%252C%2522activeTabId%2522%253A%2522clooup2gm00022e6g4x30igw6%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clooup2gm00022e6g4x30igw6%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fkubb.config.js%2522%252C%2522id%2522%253A%2522cloouy19z03xs2e6gjq64i1je%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpackage-lock.json%2522%252C%2522id%2522%253A%2522cloouyam7042u2e6gs6erwrji%2522%252C%2522mode%2522%253A%2522temporary%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%257D%252C%2522clooup2gm00062e6gpm7des8q%2522%253A%257B%2522id%2522%253A%2522clooup2gm00062e6gpm7des8q%2522%252C%2522activeTabId%2522%253A%2522clooup3jw006u2e6gtpqh92wb%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522PROJECT_SETUP%2522%252C%2522id%2522%253A%2522clooup3jw006u2e6gtpqh92wb%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522clooup2gm00052e6gdxqbxliy%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clooup2gm00042e6gbv28jy7p%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clooup2ry0036efh74qvbbnpm%2522%257D%255D%252C%2522id%2522%253A%2522clooup2gm00052e6gdxqbxliy%2522%252C%2522activeTabId%2522%253A%2522clooup2gm00042e6gbv28jy7p%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by madi-tracksuit** [comment]
Hmm okay sorry for the false alarm! Thought it could have been our monorepo setup but forked that codesandbox and still couldn't repro. Assuming gremlins our side, will close this one out

**Comment by madi-tracksuit** [comment]
Just a quick follow up, turns out I was hitting this issue https://github.com/cosmiconfig/cosmiconfig/issues/312

There's an error somewhere in my config (still figuring that one out...) and cosmic was throwing the generic require error
