### ISSUE TITLE
[swagger-ts] requestBody types not exported in the operation's ts file

### ISSUE THREAD

**Issue by davidbarral** [kubb-project/kubb#603]
### What version of `kubb` is running?

1.14.6

### What platform is your computer?

MacOS

### What steps can reproduce the bug?

1. Clone the project repo. 
2. Install packages.
3. Run the tests. 
4. Check `OperationGenerator.test.ts.snap`. It's missing the t[ypes related to the request part of the `petStore.yaml`  schema](https://github.com/kubb-project/kubb/blob/d332520891e740bb15f8a36e1bb70ec175716903/packages/swagger-ts/mocks/petStore.yaml#L46-L59):

```
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - 'name'
                - 'tag'
              properties:
                name:
                  type: string
                tag:
                  type: string
```

### How often does this bug happen?

None

### What is the expected behavior?

The test snapshot should contain an export for the `Request` type

```diff
diff --git a/packages/swagger-ts/src/generators/__snapshots__/OperationGenerator.test.ts.snap b/packages/swagger-ts/src/generators/__snapshots__/OperationGenerator.test.ts.snap
index de1a1eaa..3f5df7e7 100644
--- a/packages/swagger-ts/src/generators/__snapshots__/OperationGenerator.test.ts.snap
+++ b/packages/swagger-ts/src/generators/__snapshots__/OperationGenerator.test.ts.snap
@@ -45,6 +45,17 @@ export type CreatePetsMutationRequest = {
   tag: string
 }
 
+export type CreatePetsMutationRequest = {
+  /**
+   * @type string
+   */
+  name: string
+  /**
+   * @type string
+   */
+  tag: string
+}
+
 export type CreatePetsMutationResponse = any | null
 
 /**
```

### Additional information

I've generated the diff by modifying the code. This is the suggested fix: 

```diff
diff --git a/packages/swagger-ts/src/generators/OperationGenerator.ts b/packages/swagger-ts/src/generators/OperationGenerator.ts
index aa06abb7..3d515519 100644
--- a/packages/swagger-ts/src/generators/OperationGenerator.ts
+++ b/packages/swagger-ts/src/generators/OperationGenerator.ts
@@ -57,6 +57,7 @@ export class OperationGenerator extends Generator<Options> {
       optionalType,
       dateType,
     })
+      .add(schemas.request)
       .add(schemas.pathParams)
       .add(schemas.queryParams)
       .add(schemas.headerParams)
@@ -102,6 +103,7 @@ export class OperationGenerator extends Generator<Options> {
       optionalType,
       dateType,
     })
+      .add(schemas.request)
       .add(schemas.pathParams)
       .add(schemas.queryParams)
       .add(schemas.headerParams)
```

I think the code is just missing the request schemas when setting up the `OperationGenerator`. I would have done a PR for this change but I've just started digging into the code and I'm not sure if I'm missing some other branch. I'm more than willing to make a PR if you want me to.

**Comment by stijnvanhulle** [comment]
@davidbarral `requestBody` is getting used for POST calls and that's why you will see [`.add(schemas.request)`](https://github.com/kubb-project/kubb/blob/d332520891e740bb15f8a36e1bb70ec175716903/packages/swagger-ts/src/generators/OperationGenerator.ts#L108) being used in the `async get` of the OperationGenerator but not [here](https://github.com/kubb-project/kubb/blob/d332520891e740bb15f8a36e1bb70ec175716903/packages/swagger-ts/src/generators/OperationGenerator.ts#L35).

Maybe I'm missing something but this is probably not an issue/bug?

**Comment by davidbarral** [comment]
You are absolutely right 🤦 . My bad. Blame it on my sleep deprivation. My problem was really elsewhere. My original test fixture had a `get` and a `requestBody` 😅 . Funny enough the validator did not complain 🤷‍♂️ .

Sorry for wasting your time 🙇‍♂️. Thanks for the quick response. It helped me find my problem anyway 😄.
