### ISSUE TITLE
Can't install on Node v18

### ISSUE THREAD

**Issue by Peterabsolon** [kubb-project/kubb#607]
### What platform is your computer?

MacOS

### How did you attempt to install or upgrade?

Tried both npm and yarn

### What do you see instead?

npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'js-runtime@0.0.6',
npm WARN EBADENGINE   required: { node: '>=20', bun: '>=1.0.0' },
npm WARN EBADENGINE   current: { node: 'v18.18.2', npm: '9.8.1' }
npm WARN EBADENGINE }

Same thing for Yarn:

yarn add v1.22.19
warning ../package.json: No license field
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
warning @kubb/core@1.14.6: The engine "pnpm" appears to be invalid.
error js-runtime@0.0.6: The engine "node" is incompatible with this module. Expected version ">=20". Got "18.18.2"
warning js-runtime@0.0.6: The engine "bun" appears to be invalid.
error Found incompatible module.

### Additional information

<img width="542" alt="image" src="https://github.com/kubb-project/kubb/assets/5757143/92374a52-c920-491d-936e-ef4ebaf03117">

**Comment by stijnvanhulle** [comment]
@Peterabsolon Seems that another package/lib I made had node set to v20 with some config for the upcoming Bun support(https://www.npmjs.com/package/js-runtime). Updated that package to also have the same node version so Kubb does not have conflicts. A new version of Kubb will follow :)

**Comment by stijnvanhulle** [comment]
https://github.com/kubb-project/kubb/releases/tag/kubb-v1.14.7 Should resolve your issue :)
