### ISSUE TITLE
[v2] Cannot find module kubb+cli@2.0.0-canary.20231030T125136

### ISSUE THREAD

**Issue by madi-tracksuit** [kubb-project/kubb#639]
### What version of `kubb` is running?

2.0.0-alpha.8

### What platform is your computer?

MacOS

### What steps can reproduce the bug?

1. Install latest kubb alpha versions
2. Try run generate
3. See error

I'm using pnpm in a monorepo, and installing the latest alpha versions of Kubb packages gives me the following error when trying to run any command

```
Cannot find module '.../node_modules/.pnpm/@kubb+cli@2.0.0-canary.20231030T125136_@types+node@20.8.10_typescript@5.2.2_u3e4ydewc22maotdhijxw465aq/node_modules/@kubb/core/utils
```

I've tried nuking the pnpm cache and node_modules to no effect. Kubb 1.x works well. Looks like it's trying to depend on a canary rather than the installed alpha?

### How often does this bug happen?

Every time

**Comment by stijnvanhulle** [comment]
@madi-tracksuit Best to reinstall Kubb with `npm i -g kubb@alpha`. It seems that the CLI is using an older version which had a bug.

**Comment by madi-tracksuit** [comment]
yup as mentioned already tried nuking node modules and reinstalling. I'm using pnpm and have it installed as a local dependency. I'll try again with `alpha.9` when I get a chance
