### ISSUE TITLE
TanStack Query v5 Example Sandbox not working

### ISSUE THREAD

**Issue by melloware** [kubb-project/kubb#649]
### What is the type of issue?

Documentation is incorrect

### What is the issue?

![image](https://github.com/kubb-project/kubb/assets/4399574/127678b1-1980-4476-b97e-e8e514a32542)

**Comment by stijnvanhulle** [comment]
@melloware Hi, seems that react-query-v5 was added to v1 which does not have support for react-query v5. With v2 we will have support but those docs have another URL: https://alpha.kubb.dev/examples/tanstack-query/react-query-v5.
