### ISSUE TITLE
format hints on strings are ignored

### ISSUE THREAD

**Issue by madi-tracksuit** [kubb-project/kubb#706]
### What version of `kubb` is running?

1.14.9

### What platform is your computer?

MacOS

### What version of external packages are you using(`@tanstack-query`, `MSW`, `React`, `Vue`, ...)

```
  "@kubb/cli": "^1.14.6",     "@kubb/swagger": "^1.14.6",     "@kubb/swagger-client": "^1.14.6",     "@kubb/swagger-faker": "^1.14.6",     "@kubb/swagger-ts": "^1.14.6",     "@kubb/swagger-zod": "^1.14.6",
```

### What steps can reproduce the bug?

- Generate zod schemas from an openapi spec that uses `format` hints on fields (eg: `date`)
- See that generated types don't follow format (`z.string()` rather than `z.coerce.date()` for `date` and `z.datetime()` for `datetime`)

### How often does this bug happen?

Every time

### What is the expected behavior?

Kubb should use format hints in openAPI to generate the correct types

**Comment by stijnvanhulle** [comment]
Can you give me an example of the part for the OpenAPI and what you expect as an object/type out of it? I'm not completely following because we normally map based on the `format`
```
 if (schema.format === 'date-time' || baseName === 'date') {
    baseItems.unshift({ keyword: zodKeywords.datetime })
  }
```
