### ISSUE TITLE
Type error with infinite query's `getNextPageParam` function

### ISSUE THREAD

**Issue by la55u** [kubb-project/kubb#754]
### What version of `kubb` is running?

2.1.3

### What steps can reproduce the bug?

Minimal repro: https://github.com/la55u/kubb-ts-bug

1. run the generator with infinite option enabled: `npm run generate`
2. inspect the output in `hooks.ts`, specifically the  `getPetByIdInfiniteQueryOptions` function

### How often does this bug happen?

Every time

### What is the expected behavior?

No type errors

### Swagger/OpenAPI file?

https://github.com/la55u/kubb-ts-bug/blob/dev/openapi.yaml

**Comment by la55u** [comment]
just noticed that the `data` returned by the infinite queries also has the wrong type. It is currently the same as the regular query's `data` type but the data is actually grouped under a `pages` array by react-query.

**Comment by stijnvanhulle** [comment]
Fixed with v2.1.4
