### ISSUE TITLE
Types are not getting filtered by `exclude` in the swagger-ts plugin

### ISSUE THREAD

**Issue by la55u** [kubb-project/kubb#760]
### What version of `kubb` is running?

2.1.6

### What platform is your computer?

Fedora Linux

### What version of external packages are you using(`@tanstack-query`, `MSW`, `React`, `Vue`, ...)

"@tanstack/react-query": "^5.17.0"

### What steps can reproduce the bug?

Minimal repro: https://github.com/la55u/kubb-ts-bug
1. make sure the exclude is added to `createSwaggerTS` in the config file
2. run `npm run generate`
3. open `models.ts` and the types are there (incorrectly)

### How often does this bug happen?

None

### What is the expected behavior?

Since these types are not used by any (non-excluded) operation they should not be included in the generated output.

### Swagger/OpenAPI file?

https://github.com/la55u/kubb-ts-bug/blob/dev/openapi.yaml

### Additional information

Not sure but it _might_ be a valid use-case to just put some type definitions in the openapi spec file to make it available for the clients without it being used in any operation. In this case a new config option might be necessary instead of fixing exclude.

**Comment by stijnvanhulle** [comment]
So far I see that the exclude is working but `exclude` will not exclude parts of `components.schemas`. To make that work we should loop over all the paths and check which ref is used and then also inside that ref check what other refs are used. It 

is not that easy to create something like this, so `exclude` will work for paths but will still generate all types found in `components.schemas`.
