### ISSUE TITLE
Zod: Recursive schema

### ISSUE THREAD

**Issue by vferak** [kubb-project/kubb#769]
### What version of `kubb` is running?

10.1.0

### What platform is your computer?

Linux

### What version of external packages are you using(`@tanstack-query`, `MSW`, `React`, `Vue`, ...)

"zod": "^3.22.2"

### What steps can reproduce the bug?

When generating zod schemas from attached OpenAPI specification, it generates unusable zod schema, because it contains self reference in its inicialization.

Result of itemSchema.ts generated from attached file.

```typescript
export const itemSchema = z.object({
    name: z.string(),
    children: z.array(z.lazy(() => itemSchema).schema) // <-- self reference to itemSchema
});
```

The typescript type is generated correctly.

```typescript
export type Item = {
    /**
     * @type string
     */
    name: string;
    /**
     * @type array
     */
    children: Item[];
};
```

### How often does this bug happen?

Every time

### What is the expected behavior?

Kubb can generate recursive Zod schemas ([example](https://github.com/colinhacks/zod#recursive-types) of implementation).

### Swagger/OpenAPI file?

Whole specification in file here: [openapi.json](https://github.com/kubb-project/kubb/files/13917693/openapi.json)

Troublesome part:
```json
"components": {
    "schemas": {
      "Item": {
        "type": "object",
        "required": ["name", "children"],
        "properties": {
          "name": {
            "type": "string"
          },
          "children": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/Item"
            }
          }
        }
      }
    }
  }
```

**Comment by stijnvanhulle** [comment]
This was fixed with `kubb` version 2.1.0, see https://github.com/kubb-project/kubb/pull/744

**Comment by vferak** [comment]
Thank you for your answer!

After updating to version 2.3.0, the code now works. :+1: 

However, Typescript is still complaining. :confused:

After compilation it throws this error:
`'itemSchema' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.`

```typescript
export const itemSchema = z.object({  // <-- ts-compile complains here
    name: z.string(),
    children: z.array(z.lazy(() => itemSchema)) // <-- self reference to itemSchema
});
```

Yes, i can ignore the whole generated folder in tsconfig, but i would like it to work.

I'm able to fix this error by adding type annotation to the schema like this:
```typescript
export const itemSchema: z.ZodType<Item> = z.object({  // <-- everything is fine now
    name: z.string(),
    children: z.array(z.lazy(() => itemSchema))
});
```
Would something like this be possible?

I know it adds another plugin dependecy to zod plugin (typescript plugin), but i think it would be worth it.

**Comment by stijnvanhulle** [comment]
@vferak This seems more like a TypeScript config issue, maybe this related Stackoverflow issue can help: https://stackoverflow.com/questions/41944650/this-implicitly-has-type-any-because-it-does-not-have-a-type-annotation.

**Comment by vferak** [comment]
The issue you linked is concerned mainly about the **this** keyword, which is not my issue.

In tsconfig i can only ignore this file or enable `any` in my codebase with `noImplicitAny` (neither of which i want).

The issue really stems from the fact, that Typescript can't infer the type of `itemSchema`, because it contains the self reference. It's clearly described in zod documentation [https://github.com/colinhacks/zod?tab=readme-ov-file#recursive-types](https://github.com/colinhacks/zod?tab=readme-ov-file#recursive-types).

_You can define a recursive schema in Zod, but because of a limitation of TypeScript, **their type can't be statically inferred. Instead you'll need to define the type definition manually, and provide it to Zod as a "type hint"**._

So as far as i can tell, adding the typehint seems like the only solution for now.

**Comment by vferak** [comment]
Can confirm, that after upgrading to version **v2.5.0** and configuring Zod with option `{ typed: true }` everything works as expected! 🥳

Detailed config solving this issue is [here](https://www.kubb.dev/plugins/swagger-zod/#typed).

Thank you very much @stijnvanhulle. 🔥

**Comment by austinlangdon** [comment]
@vferak what package did you need to upgrade to resolve the issue? v2.50 of what?

**Comment by austinlangdon** [comment]
Thank you @stijnvanhulle I added `typed: true` to the config, but the error still persisting.

Only thing that helping is removing .schema reference

Changing this:

`z.lazy(() => metadataValueSchema.schema)`

to

`z.lazy(() => metadataValueSchema)`

I noticed https://github.com/kubb-labs/kubb/pull/744 (fix: removal of .schema) did this as well

Why would .schema still be appended within lazy()?

**Comment by vferak** [comment]
@austinlangdon yes, the **.schema** reappeared in our schemas, which also broked our generated code :confused:.

Hovewer, after upgrading to Kubb **v2.19.1**, they are once again gone :grinning:.

So i recommend upgrading to fix this issue :slightly_smiling_face:.
