### ISSUE TITLE
TanstackQuery: Infinite query page parameter is not always a number

### ISSUE THREAD

**Issue by mpetito** [kubb-project/kubb#779]
### What is the problem this feature would solve?

The options for infinite query generation include an `initialPageParam` which assumes a number is used (e.g. a page number).

There are scenarios where the parameter is not a number (for ex., with cursor-based pagination).

### What is the feature you are proposing to solve the problem?

The initial page parameter should accept numbers or strings as possible values.

It would also be necessary to infer the parameter type based on the provided value.  This may be tricky if the initial value should be undefined, since no value is known until the first page is fetched.

### What alternatives have you considered?

The current template seems to emit the configured value as-is, so I am using this workaround:

`initialPageParam: 'undefined as string | undefined' as unknown as number,`

Which generates:

```
        initialPageParam: undefined as string | undefined,
        getNextPageParam: (lastPage) => lastPage["nextPageToken"],
```

**Comment by stijnvanhulle** [comment]
Are you using v4 or v5 of `@tanstack/query`?

**Comment by mpetito** [comment]
I'm on @tanstack/react-query 5.13.4 and @kubb/swagger-tanstack-query 2.1.6

**Comment by stijnvanhulle** [comment]
Based on the documentation of `@tanstack/query` I see that `initialPageParam` is unknown meaning it can be a string, number,...

I will open a PR to have the same type so you are unblocked.

https://github.com/TanStack/query/blob/96cdb28d311772774323c05a75372ed05eedfde8/packages/query-core/src/types.ts#L180
