### ISSUE TITLE
use es2015 module syntax instead of ts namespace

### ISSUE THREAD

**Issue by chiptus** [kubb-project/kubb#787]
### What is the problem this feature would solve?

our tsconfig disallows the use of namespace: `export namespace AuthenticateUserMutation`, eslint suggests `ES2015 module syntax is preferred over namespaces.`

### External documents/projects?

https://typescript-eslint.io/rules/no-namespace/

### What alternatives have you considered?

allow namespaces in the generated files. but I don't see how these namespaces are being used

**Comment by stijnvanhulle** [comment]
For now, it was not being used but it was an idea to use this as an easier way of getting a response/request type.
So I will replace it with just types(no issues with Eslint + better to not have namespaces)

Before
```typescript
export namespace FindPetsByStatusQuery {
  export type Response = FindPetsByStatusQueryResponse
  export type QueryParams = FindPetsByStatusQueryParams
  export type Errors = FindPetsByStatus400
}

type Test = FindPetsByStatusQuery.Errors
``` 
After
```typescript
export type FindPetsByStatusQuery ={
  Response: FindPetsByStatusQueryResponse
  QueryParams:FindPetsByStatusQueryParams
 Errors:FindPetsByStatus400
}

type Test = FindPetsByStatusQuery["Errors"]
```
