### ISSUE TITLE
a main barrel export is created even when the config is disabled

### ISSUE THREAD

**Issue by chiptus** [kubb-project/kubb#789]
### What version of `kubb` is running?

2.4.0

### What platform is your computer?

codesandbox

### What steps can reproduce the bug?

see sandbox https://codesandbox.io/p/devbox/kubb-playbox-5g2n53?file=%2Fgen%2Findex.ts%3A1%2C55

### How often does this bug happen?

Every time

### What is the expected behavior?

no main barrel export

**Comment by stijnvanhulle** [comment]
When used with the `group` option it broke the logic causing the index.ts files to be created. 
I opened a PR to also check on the barrelType so no barrel files would be created.
