### ISSUE TITLE
refs with `.` inside, won't be imported correctly to zod schemas

### ISSUE THREAD

**Issue by chiptus** [kubb-project/kubb#792]
### What version of `kubb` is running?

2.4.0

### What platform is your computer?

codesandbox

### What steps can reproduce the bug?

see codesandbox https://codesandbox.io/p/devbox/kubb-playbox-5g2n53?file=%2Fswagger.yaml%3A81%2C25

you can see that type `pet.Pets` is converted to `PetPets`, and in `petPetsSchema`, the import is not correct

### How often does this bug happen?

Every time

### What is the expected behavior?

either the import stays correct and the generated type is in `./gen/pet/Pets.ts`, or the input should be corrected

**Comment by stijnvanhulle** [comment]
@chiptus I will change this so that `pet.Pets` will be created inside of `src/pet/Pets.ts` instead of what is happening now(`src/pets.ts).

**Comment by chiptus** [comment]
That's the expected behavior imo, thanks!
