### ISSUE TITLE
Support for native Enums in `@kubb/swagger-zod`

### ISSUE THREAD

**Issue by chiptus** [kubb-project/kubb#802]
### What version of `kubb` is running?

2.5.0

### What platform is your computer?

codesandbox

### What steps can reproduce the bug?

https://codesandbox.io/p/devbox/kubb-playbox-5g2n53 with https://github.com/kubb-project/kubb/blob/main/e2e/schemas/petStore.yaml

see `gen/orderSchema.ts`

### How often does this bug happen?

None

### What is the expected behavior?

maybe:
1. `z.nativeEnum(OrderStatus)`
2. ` z.enum([OrderStatus.placed, OrderStatus.approved, OrderStatus.delivered])`

the first solution is probably easier, but what if our API limits the options to a subset of the enum

**Comment by stijnvanhulle** [comment]
To resolve this for now I would suggest adding a casting

```
export const orderSchema = z.object({
  'id': z.number().optional(),
  'petId': z.number().optional(),
  'quantity': z.number().optional(),
  'shipDate': z.date().optional(),
  'status': z.enum([`placed`, `approved`, `delivered`]).describe(`Order Status`).optional(),
  'http_status': z.union([z.literal(200), z.literal(400)]).describe(`HTTP Status`).optional(),
  'complete': z.boolean().optional(),
}) as z.ZodType<Order>
```

**Comment by chiptus** [comment]
> To resolve this for now I would suggest adding a casting

do you mean manually?

**Comment by stijnvanhulle** [comment]
@chiptus No no, the casting will be added by Kubb so you don't need to care about it. The only thing here is that Kubb then will use casting which is of course not great but as a temporary solution I think that would be fine(so you can at least continue).
