### ISSUE TITLE
Add override option to swagger-faker

### ISSUE THREAD

**Issue by karlismelderis-mckinsey** [kubb-project/kubb#805]
### What is the problem this feature would solve?

very often there is a need to set some data to fixed value due to nature of tests

currently faker code looks like this:
```ts
export function createPerson(): NonNullable<Person> {
  return {
    contact: createContact(),
    core: createCore(),
    personal: createPersonal(),
    isPresident: createIsPresident(),
  };
}
```

to create a reusable fake data for Mr. President we need to create extra helper function:
```ts
const createMrPresident => () => {
  const data = createPerson()
  return {
    ...data,
    isPresident: true
  }
}
```

to support option to override faker data in more generic way we need to maintain such helper function:
```ts
const createMrPresident => (overrides: Partial<Person>) => {
  const data = createPerson()
  return {
    ...data,
    ...overrides,
  }
}
```

it would be great if generated faker functions would already support overrides and save us from maintaining our own "override" functions

**Comment by stijnvanhulle** [comment]
@karlismelderis-mckinsey We don't have a way of overriding the generated faker functionality but what you can do is use `seed`. This will make sure that the returned data is always the same random data.


https://fakerjs.dev/api/randomizer.html#seed
https://www.kubb.dev/plugins/swagger-faker/#seed

**Comment by karlismelderis-mckinsey** [comment]
I'm aware of seed in fakerjs but it doesn't give us option to set some values to fixed data and let the rest be random

Would you be interested adding such change or we are stuck with our helper functions?

**Comment by stijnvanhulle** [comment]
@karlismelderis-mckinsey So if I'm understanding it correctly, Kubb should return the following code:
```
export function createPerson(override: Partial<Person>): NonNullable<Person> {
  return {
    contact: createContact(),
    core: createCore(),
    personal: createPersonal(),
    isPresident: createIsPresident(),
    ...override
  };
}
```

**Comment by karlismelderis-mckinsey** [comment]
> @karlismelderis-mckinsey So if I'm understanding it correctly, Kubb should return the following code:
> 
> ```
> export function createPerson(override: Partial<Person>): NonNullable<Person> {
>   return {
>     contact: createContact(),
>     core: createCore(),
>     personal: createPersonal(),
>     isPresident: createIsPresident(),
>     ...override
>   };
> }
> ```

👍
That's exactly we're looking for
