### ISSUE TITLE
Allow to add some unique value to queryKey template for a particular service/domain at the beginning of an array

### ISSUE THREAD

**Issue by oskar-dragon** [kubb-project/kubb#811]
### What is the problem this feature would solve?

The problem that this feature would solve is the limitation in the React Query template for overriding the default objectKeys function. Currently, it does not allow passing the name of the service/domain to the queryKeys template to make it more unique. This limitation becomes problematic when working with microservices, making requests to multiple endpoints, and dealing with situations where some endpoints between services are the same but different base URLs.

By allowing the inclusion or passing some kind of unique value to it, such as the service/domain name to the queryKeys template, developers would have more flexibility and control over how queries are defined and make sure they are more unique, or are more descriptive to them, especially in scenarios where endpoints may share the same name across different services.

This enhancement would facilitate a more modular and customisable approach to managing query keys, enabling developers to handle diverse scenarios.

### What alternatives have you considered?

The current workaround involves creating a factory function to generate a React component queryKey template. This factory function accepts a unique value, which is then added to the beginning of an array in the template. However, the process requires manual copying and pasting or utilising a tool like Plop to generate a new template whenever a new service is added.

This is what we currently have to do:

```ts
import type { QueryKey } from '@kubb/swagger-tanstack-query/components';
import React from 'react';
import { APIServiceName } from '@/utils/api';
import { Function, Type } from '@kubb/react';

export const queryKeyTemplateFactory = (serviceName: APIServiceName) => {
  return function QueryKeyTemplate({
    name,
    generics,
    returnType,
    params,
    JSDoc,
    keys,
  }: React.ComponentProps<typeof QueryKey.templates.react>) {
    function toPascalCase(input: string): string {
      // Remove non-alphanumeric characters and split the string into words
      const words = input.replace(/[^a-zA-Z0-9]/g, ' ').split(' ');

      // Capitalize the first letter of each word and join them
      const pascalCaseString = words.map((word) => word.charAt(0).toUpperCase() + word.slice(1)).join('');

      return pascalCaseString;
    }
    return (
      <>
        <Function name={name} export generics={generics} returnType={returnType} params={params} JSDoc={JSDoc}>
          {`return ['service.${serviceName}', ${keys}] as const`}
        </Function>
        <Type name={toPascalCase(name)}>{`ReturnType<typeof ${name}>`}</Type>
      </>
    );
  };
};
```

And for every new service, we have to create a new file like below
```ts
import { PluginOptions } from '@kubb/swagger-tanstack-query';

import { queryKeyTemplateFactory } from '../queryKeyTemplateFactory';

export const templates: PluginOptions['options']['templates'] = {
  queryKey: {
    react: queryKeyTemplateFactory('INVOICES'),
  },
};
```

**Comment by oskar-dragon** [comment]
@stijnvanhulle I just want to check if there are any updates on this?

**Comment by stijnvanhulle** [comment]
@oskar-dragon you can now use `query.queryKey` to override the generated queryKey. See https://www.kubb.dev/plugins/swagger-tanstack-query/#query-querykey
