### ISSUE TITLE
Add Response access to SDK generated (server/client)

### ISSUE THREAD

**Issue by b-barry** [kubb-project/kubb#812]
### What is the problem this feature would solve?

Currently, the SDKs generated by Kubb from our OpenAPI specifications only allow access to the parsed response data, which is typically the result of `response.json()`. This restricts us from accessing the full Response object, including headers and cookies, which are essential for certain backend functionalities, such as session management.

### External documents/projects?

Our project relies on cookie-based session handling which requires access to the `Set-Cookie` header in the HTTP response. The inability to access this within the generated SDK impacts our authentication flow.

### What is the feature you are proposing to solve the problem?

I propose an enhancement to the SDK generation feature of Kubb that allows developers to opt-in to receive the full HTTP Response object. This could be facilitated through a configuration option such as `returnFullResponse`, which when enabled, would adjust the generated SDK methods to return the entire Response object.

**Comment by stijnvanhulle** [comment]
You can set the `dataReturnType` to `full` to access the ResponseConfig instead of just the data.
See https://www.kubb.dev/plugins/swagger-tanstack-query/#datareturntype

**Comment by b-barry** [comment]
Thanks sorry for the issue. Closing it
