### ISSUE TITLE
TS4023: Exported variable 'definePlugin' has or is using name 'Cache' from external module

### ISSUE THREAD

**Issue by pafnuty** [kubb-project/kubb#838]
### What version of `kubb` is running?

2.6.6

### What platform is your computer?

Windows

### What steps can reproduce the bug?

1. Write the minimum amount of code needed to create your own plugin.
2. Try to run the code build.

### How often does this bug happen?

Every time

### What is the expected behavior?

The plugin builds without errors

### Additional information

I'm trying to create my own plugin for kubb, I get an error when I try to build the plugin:
```bash
src/plugin.ts(6,14): error TS4023: Exported variable 'definePlugin' has or is using name 'Cache' from external module "path_to/node_modules/@kubb/c
ore/dist/index" but cannot be named.
```
I made a repository with a minimal amount of code that reproduces the error:  https://github.com/pafnuty/kubb-plugin-template-error

If I go to the `node_modules/@kubb/c
ore/dist/index.d.ts` file and add export to `interface Cache`, the build happens without error.

Unfortunately I have no idea how to fix this, so I can't offer a PR :(

**Comment by stijnvanhulle** [comment]
`v2.6.7` will resolve this issue. Seems that we were not exporting all types and for the `definePlugin` that will be needed.

**Comment by pafnuty** [comment]
It's all working now!
Thank you so much!!!
