### ISSUE TITLE
auto generated models break when descriptor contains enum whose name equals the qualified name of a schema property

### ISSUE THREAD

**Issue by fauxbytes** [kubb-project/kubb#841]
### What version of `kubb` is running?

kubb/2.7.0 win32-x64 node-v18.16.0

### What platform is your computer?

win

### What version of external packages are you using(`@tanstack-query`, `MSW`, `React`, `Vue`, ...)

n/a (bare kubb)

### What steps can reproduce the bug?

kubb.config.ts:
```
{
        root: '.',
        output: {path: './src/openapi/pets', clean: true},
        plugins: [
            ['@kubb/swagger', {output: false, validate: true}],
            ['@kubb/swagger-ts', {output: {path: 'models.ts'}, enumType: 'enum', dateType: 'string'}],
        ],
        input: {path: 'petStore.yaml'},
    }
```
Modified `examples/typescript/petStore.yaml` from [kubb repo](https://github.com/kubb-project/kubb/blob/main/examples/typescript/petStore.yaml), as-per attached patch.

Resulting `models.ts` declares `OrderType` twice:
```
//...
 export enum OrderType {
    "placed" = "placed",
    "approved" = "approved",
    "delivered" = "delivered"
}
//....
 export enum OrderType2 {
    "foo" = "foo",
    "bar" = "bar"
}
export type OrderType = OrderType2;
//...
}
```
[gen_breaks_when_descriptor_contains_enum_whose_name_equals_the_qualified_name_of_a_schema_.patch](https://github.com/kubb-project/kubb/files/14488569/gen_breaks_when_descriptor_contains_enum_whose_name_equals_the_qualified_name_of_a_schema_.patch)

### How often does this bug happen?

Every time

**Comment by stijnvanhulle** [comment]
This is not easy to do because we use the `schemaName` for the type append the key(if the type is `object`). If that combination is already(not unique enough) there because another type has the same name, we add a number to make it unique. Not sure what else we can do there or what we can use coming from the OpenAPI/Swagger file.

**Comment by fauxbytes** [comment]
Seems to me the problem is more related to the alias declaration:
```

**Comment by fauxbytes** [comment]
Would adopting `openapi-generator`s approach work? Seems like they append an "Enum" suffix to an enum property. This would yield:
```
export enum OrderType {
    Foo = 'foo',
    Bar = 'bar'
}
//...
export interface Order {
    //...
    type?: OrderTypeEnum;
    //...
}

export enum OrderTypeEnum {
    Placed = 'placed',
    Approved = 'approved',
    Delivered = 'delivered'
}
```

and do away with the type aliasing
