### ISSUE TITLE
Kubb TypeScript config format does not work with defineConfig as described in the documentation on 2.7.0

### ISSUE THREAD

**Issue by CIP43R** [kubb-project/kubb#843]
### What version of `kubb` is running?

2.7.0

### What platform is your computer?

MacOS

### What version of external packages are you using(`@tanstack-query`, `MSW`, `React`, `Vue`, ...)

Vue 3.4.15, Vite 5.0.12

### What steps can reproduce the bug?

- Install @kubb/cli 2.7.0 (or use npx) as well as core, swagger, swagger-ts or swagger client of the same version on a fresh vite environment
- Provide a basic config as provided in the [docs](https://www.kubb.dev/guide/configure#multiple-configs) as TypeScript file
- Use the command `kubb generate --log-level info` or `npx @kubb/cli generate --log-level info`

It does not matter if an existing api specification json is provided, the error occurs before fetching the json as it is a JavaScript error.
[CodeSandbox](https://codesandbox.io/p/devbox/kubb-bug-rk5nhx?file=%2Fkubb.config.ts%3A27%2C32)
I provided different scripts to see the difference of the versions regarding the same configs with just different extensions (even though type is set to module in the package json). Changing the export of the config to a constant or using an non async function does not change anything.

### How often does this bug happen?

Every time

### What is the expected behavior?

It should generate the code as it did with the exact same configuration on version 2.6.7

### Additional information

Depending on which plugin(s) used, the error will slightly vary (import_swagger.default is not a function, import_swagger_ts.default is not a function etc.)

**Comment by stijnvanhulle** [comment]
Version `2.7.1` will resolve this :)

**Comment by CIP43R** [comment]
> Version `2.7.1` will resolve this :)

Awesome! I love the constant progress on this project. I'm gonna suggest my company to sponsor it soon :D
