### ISSUE TITLE
[swagger-zod] Generate mapping of `operationId` to request / response fields

### ISSUE THREAD

**Issue by mitchell-merry** [kubb-project/kubb#847]
### What is the problem this feature would solve?

I want to be able to get the request / response schemas for a particular operation by simply providing an operationId.

### External documents/projects?

I don't understand the question. openapi-typescript does this, and it's extremely useful: https://github.com/drwpow/openapi-typescript/blob/main/packages/openapi-typescript/examples/digital-ocean-api.ts#L15124

### What is the feature you are proposing to solve the problem?

We should generate `paths`, `operations`, etc... that look like this:

```ts
export const operations = {
  "myOperationOne": {
    parameters: {
      query: myOperationOneQueryParamsSchema;
    };
    responses: {
      200: myOperationOne200Schema;
    };
  },
  "myOperationOne": ...,
} as const;

export const paths = {
  "/some/path": {
    get: operations["myOperationOne"];
    post: operations["myOperationTwo"];
  },
} as const;
```

this way I can just `operations[operationId]...`

**Comment by stijnvanhulle** [comment]
When using `@kubb/swagger-client` you will get a `operations.ts` file.
```
export const operations = {
  'createPets': { 'path': '/pets/:uuid', 'method': 'post' },
  'updatePet': { 'path': '/pet', 'method': 'put' },
  'addPet': { 'path': '/pet', 'method': 'post' },
  'findPetsByStatus': { 'path': '/pet/findByStatus', 'method': 'get' },
  'findPetsByTags': { 'path': '/pet/findByTags', 'method': 'get' },
  'getPetById': { 'path': '/pet/:petId', 'method': 'get' },
  'updatePetWithForm': { 'path': '/pet/:petId', 'method': 'post' },
  'deletePet': { 'path': '/pet/:petId', 'method': 'delete' },
  'uploadFile': { 'path': '/pet/:petId/uploadImage', 'method': 'post' },
  'createUser': { 'path': '/user', 'method': 'post' },
  'createUsersWithListInput': { 'path': '/user/createWithList', 'method': 'post' },
  'loginUser': { 'path': '/user/login', 'method': 'get' },
  'logoutUser': { 'path': '/user/logout', 'method': 'get' },
  'getUserByName': { 'path': '/user/:username', 'method': 'get' },
  'updateUser': { 'path': '/user/:username', 'method': 'put' },
  'deleteUser': { 'path': '/user/:username', 'method': 'delete' },
} as const
```

**Comment by mitchell-merry** [comment]
We don't use `zodios` and I don't want to introduce it into our (server only) backend (it's not something that should be necessary just to generate this simple mapping).

Unfortunately I specifically need a mapping of operationId to Zod schema.

**Comment by stijnvanhulle** [comment]
@mitchell-merry I'm thinking of creating one that also can be used by the Zodios generator(less generation needed then). I am planning this for the coming week.

**Comment by mitchell-merry** [comment]
As long as I can get it without needing zodios generation, I'm happy :D thank you!

**Comment by mitchell-merry** [comment]
This is great! Though, there's exactly one missing feature that we need to fully adopt this (I apologise for not realising this earlier), and I had a look and this may be hard to implement; for the body, we need the name of the parameter it was given in Swagger 2.0. For example, in the below snippet, we would somehow need to know that the name of the body is `payload` since we have some middleware that does transformations based on that name.

```yaml
- name: payload
  in: body
  schema: { ... }
```

A simple enough solution (at least for this use-case) would be to provide a `requestBodyName: ...` field in the operations mapping so that we can do this. But I had a look through the code to see if this would be difficult, and correct me if I'm wrong, it looks like the 2.0 schema is converted to 3.x, and when this happens, the name is _lost_ (since 3.x doesn't have support for naming the body), so it's not as simple as pulling it out of the schema when we construct the mapping.

We could resolve this by writing a little script ourselves to generate a .ts file with this mapping separately, but we would very much like to avoid this if possible. Do you think this is doable?
