### ISSUE TITLE
faker plugin produces floats for integer type

### ISSUE THREAD

**Issue by samhh** [kubb-project/kubb#858]
### What version of `kubb` is running?

2.8.0

### What steps can reproduce the bug?

Given spec containing:

```json
{
  "foo": {
    "type": "integer"
  }
}
```

The plugin outputs roughly:

```ts
export function createFooResponse(): GetFooResponse {
  return faker.helpers.arrayElements([{ "foo": faker.number.float({}) }])
}
```

### How often does this bug happen?

Every time

### What is the expected behavior?

`faker.number.int`

**Comment by stijnvanhulle** [comment]
Fixed with Kubb `v2.8.1`
