### ISSUE TITLE
Running `kubb` doesn't work with `yarn` or `npx`

### ISSUE THREAD

**Issue by dnlgrgly** [kubb-project/kubb#888]
### What version of `kubb` is running?

n/a

### What platform is your computer?

macOS 14.4.1

### What steps can reproduce the bug?

This is my first time trying to use this package, so I'm sorry if this is a bit dumb. I tried several ways of getting and installing the package. Eg. `yarn global add kubb` or `yarn global add @kubb/cli`, which installs fine, but when trying to run it in a project with a `kubb.config.ts`, I receive this error:

```
daniel@mbp app % kubb
/Users/daniel/.config/yarn/global/node_modules/kubb/node_modules/@kubb/cli/dist/index.cjs:11
var ora = require('ora');
          ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/daniel/.config/yarn/global/node_modules/kubb/node_modules/ora/index.js from /Users/daniel/.config/yarn/global/node_modules/kubb/node_modules/@kubb/cli/dist/index.cjs not supported.
Instead change the require of index.js in /Users/daniel/.config/yarn/global/node_modules/kubb/node_modules/@kubb/cli/dist/index.cjs to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/Users/daniel/.config/yarn/global/node_modules/kubb/node_modules/@kubb/cli/dist/index.cjs:11:11) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v18.18.2
```

Running `npx kubb` results in:

```
✖   Error: Cannot find module '@tsconfig/react-native'
  Require stack:
  - /Users/daniel/.../app/node_modules/load-tsconfig/dist/index.js
```

The documentation says I should just install the package in the project and then run the command but I'm not sure how that would work, as then I receive the usual `zsh: command not found 'kubb'` error.

### How often does this bug happen?

Every time

**Comment by stijnvanhulle** [comment]
@dnlgrgly Can you provide me with some more information about what your `package.json` looks like(are you using ESM or CJS) and if possible can you create a Codesandbox? I'm trying to reproduce this.

**Comment by Downchuck** [comment]
It's a sensitive one - the CLI will run but it's real quick to lose to packaging:

```
[!] SyntaxError: Named export 'orderBy' not found. The requested module 'natural-orderby' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'natural-orderby';
const { orderBy } = pkg;

./AppData/Local/Yarn/Berry/cache/@kubb-react-npm-2.26.3-febeadb4d4-10c0.zip/node_modules/@kubb/react/dist/chunk-OH6PKTNL.js:20
import { orderBy } from "natural-orderby";
         ^^^^^^^
```
