### ISSUE TITLE
Unknown option `--config`

### ISSUE THREAD

**Issue by fredericrous** [kubb-project/kubb#893]
### What version of `kubb` is running?

2.11.1

### What platform is your computer?

MacOS

### What steps can reproduce the bug?

documentation should be updated to reflect correct usage of kubb.

`--config` option doesn't exist, `--help` reveals we should just do `kubb my-config-file`

reproduction workflow

- go to `https://docs.kubb.dev/guide/quick-start`
- create the file kubb.config.js as indicated
- run the bash command `kubb --config kubb.config.js` as written in the doc

result:

```
✗ npx kubb --config kubb.config.ts                                                                                                                                          15:30:23
✖   Error: Unknown option `--config`
```
 

### How often does this bug happen?

None

**Comment by fredericrous** [comment]
I meant to put the documentation label, sry I can't edit

**Comment by stijnvanhulle** [comment]
@fredericrous `kubb` was used as an alias for `kubb generate` but the options were not passed through. V2.12.0 will resolve this.
