### ISSUE TITLE
Error downloading...HTTP ERROR 404 (plugin: swagger, hook: buildStart) (plugin: swagger, hook: buildStart)

### ISSUE THREAD

**Issue by fredericrous** [kubb-project/kubb#896]
### What version of `kubb` is running?

2.11.1

### What platform is your computer?

MacOS

### What steps can reproduce the bug?

use the following kubb config

```js
import { defineConfig } from '@kubb/core'
import createSwagger from '@kubb/swagger'
import createSwaggerZod from '@kubb/swagger-zod'

export default defineConfig({
  root: '.',
  input: {
    path: 'https://docs.machines.dev/f6613bcb-f25d-4d73-9346-87d3d071e637',
  },
  output: {
    path: './src/gen',
    // clean: true,
  },
  //hooks: {
  //  done: ['echo "🎉 done"'],
  //},
  plugins: [
    createSwagger({}),
    createSwaggerZod({
      output: {
        path: './zod',
      },
    }),
  ],
})

```

run `kubb`, notice the error

```console
✖   Error: Error downloading https://docs.machines.dev/f6613bcb-f25d-4d73-9346-87d3d071e637 
  HTTP ERROR 404 (plugin: swagger, hook: buildStart) (plugin: swagger, hook: buildStart)
```

### How often does this bug happen?

Every time

**Comment by stijnvanhulle** [comment]
<img width="751" alt="Screenshot 2024-03-31 at 4 14 46 PM" src="https://github.com/kubb-project/kubb/assets/5904681/5f205ee4-b52a-4d72-adfc-99742a9761df">
Nothing we can do here, the URL is returning a 404.

**Comment by fredericrous** [comment]
correct, the documentation tool they use, scalar, seems to generate the url on the fly. correct url is https://docs.machines.dev/spec/openapi3.json
