### ISSUE TITLE
Nice project

### ISSUE THREAD

**Issue by anymaniax** [kubb-project/kubb#90]
Hello @stijnvanhulle, it's a really nice project and I really like the way you structured it. What do you think about helping me on [orval](https://github.com/anymaniax/orval) or merging our project somehow? I don't have a lot of time to maintain and improve it so would be great to combine forces. Let me know what you think about this.

**Comment by stijnvanhulle** [comment]
@anymaniax Thank you very much 💯 . At this moment, I'm not yet sure about the future. It started as a tryout to make a plugin system around creating generated code. That changed a little bit, now it's a tool to generate React-Query hooks, Axios controller and Zod schemas out of a Swagger file. 
For now, it's more like a hobby project so maybe later in the future, we can combine/integrate Orval.

**Comment by anymaniax** [comment]
What do you think about having a discussion on discord or something else one day? We can even see each other around a beer if you want since we are both from Belgium 😅
