### ISSUE TITLE
swaggerTS generates types but not the functions

### ISSUE THREAD

**Issue by fredericrous** [kubb-project/kubb#910]
### What version of `kubb` is running?

2.12.1

### What platform is your computer?

MacOS

### What steps can reproduce the bug?

use the following kubb.config.ts

```js
import { defineConfig } from '@kubb/core'
import { definePlugin as createSwagger } from '@kubb/swagger'
import { definePlugin as createSwaggerTS } from '@kubb/swagger-ts'

export default defineConfig({
  root: '.',
  input: {
    path: 'https://docs.machines.dev/spec/openapi3.json',
  },
  output: {
    path: './src/gen',
    clean: true,
  },
  plugins: [
    createSwagger({ validate: false }),
    createSwaggerTS({
      output: {
        path: 'fly-api.ts',
      },
    }),
  ],
})
```

run `kubb generate`

### How often does this bug happen?

Every time

### What is the expected behavior?

generates the types and the function

**Comment by stijnvanhulle** [comment]
What do you mean with functions? The API client(axios.get, axios.put)?

**Comment by stijnvanhulle** [comment]
@fredericrous Aah okaay. `@kubb/swagger/ts` will only generate types and enums. To call an API endpoint you also need https://docs.kubb.dev/plugins/swagger-client/. That one will use `@kubb/swagger/ts` to generate some get/post/put helpers.

Example: https://docs.kubb.dev/examples/client

(I'm working on an update for the docs with an example of using the clients)
