### ISSUE TITLE
[@kubb/swagger-zod] Better datetime schema validation

### ISSUE THREAD

**Issue by vferak** [kubb-project/kubb#918]
### What is the problem this feature would solve?

Currently, Kubb can generate Zod schema with string datetime validation.

Example OpenAPI schema:
```json
"Date": {
  "required": ["date"],
  "properties": {
    "date": {
      "type": "string",
      "format": "date-time"
    }
  },
  "type": "object"
}
```
Generated Zod schema:
```ts
export const dateSchema = z.object({
    date: z.string().datetime(),
});
```

However, this works only for ISO 8601 without timezone offsets ([zod docs](https://zod.dev/?id=iso-datetimes)).

Due to the fact, that timezone offsets are pretty common, it would be nice, if kubb could generate zod schema, that would validate it correctly, because in its current state, this datetime gets flagged as invalid **2020-01-01T00:00:00+02:00**.

### What is the feature you are proposing to solve the problem?

I can think of three different solutions:

1) **Enable zod datetime offset option by default**

Kubb could always create zod string datetime schema with option **offset** set to **true**, because it only adds offsets as being valid, without invalidating any previous formats.

It's already being done by default in openapi-zod-client library ([src](https://github.com/astahmer/openapi-zod-client/blob/main/lib/src/openApiToZod.ts#L391)).

Expected Zod schema:
```ts
export const dateSchema = z.object({
    date: z.string().datetime({ offset: true }),
});
```

2) **Add zod datetime offset option to kubb config**

This would require tweaking already existing **dateType** config. I'm thinking something similiar to this:
```ts
createSwaggerZod({
    dateConfig: {
        type: 'string' | 'date',
        offset: boolean,
    },
}),
```
Expected Zod schema:
```ts
export const dateSchema = z.object({
    date: z.string().datetime({ offset: kubb.config.offset.value }),
});
```

Two issues with this approach:
- It only works for type 'string', for type 'date' it gets ignored.
- You are basicaly copying zod config options to kubb config options, which is probably unwanted.

3) **Add an option to disable zod datetime validation to kubb config**

This one doesn't solve the original issue, but it allows usage of kubb on OpenAPI schemas, that contain date-time values. It could just be a **false** value added to already existing dateType config option, which would not generate any datetime validation.

Example Kubb config:
```ts
createSwaggerZod({
    dateType: false,
}),
```

Expected Zod schema:
```ts
export const dateSchema = z.object({
    date: z.string(),
});
```

**Comment by stijnvanhulle** [comment]
We will add a new type to `dateType` called `stringOffset` that will set the offset to true. 
In the next major release of Kubb we will set the default to `stringOffset`.

### Example
```
 createSwaggerZod({
        output: {
          path: './zod',
          exportAs: 'zod',
        },
        exclude: [
          {
            type: 'tag',
            pattern: 'store',
          },
        ],
        group: { type: 'tag' },
        dateType: 'stringOffset',
        typed: true,
      }),
```
Generates:
```
export const orderSchema = z.object({
  id: z.number().optional(),
  petId: z.number().optional(),
  quantity: z.number().optional(),
  orderType: z.enum(['foo', 'bar']).optional(),
  type: z.string().describe('Order Status').optional(),
  shipDate: z.string().datetime({ offset: true }).optional(),
  status: z.enum(['placed', 'approved', 'delivered']).describe('Order Status').optional(),
  http_status: z
    .union([z.literal(200), z.literal(400)])
    .describe('HTTP Status')
    .optional(),
  complete: z.boolean().optional(),
})
```

**Comment by stijnvanhulle** [comment]
https://kubb.dev/plugins/swagger-zod/#datetype
