### ISSUE TITLE
All objects and properties return optional values 

### ISSUE THREAD

**Issue by Samuel-Morgan-Tyghe** [kubb-project/kubb#930]
### What version of `kubb` is running?

kubb/2.12.3 darwin-arm64 node-v18.19.1

### What platform is your computer?

MACOS
### What version of external packages are you using(`@tanstack-query`, `MSW`, `React`, `Vue`, ...)

    "@kubb/cli": "^2.12.3",
    "@kubb/core": "^2.12.3",
    "@kubb/swagger": "^2.12.3",
    "@kubb/swagger-client": "^2.12.3",
    "@kubb/swagger-faker": "^2.12.3",
    "@kubb/swagger-msw": "^2.12.3",
    "@kubb/swagger-tanstack-query": "^2.12.3",
    "@kubb/swagger-ts": "^2.12.3",
    "@kubb/swagger-zod": "^2.12.3",
    
    
### What steps can reproduce the bug?

When i paste the JSON of my swagger docs into alternative tools the objects and thier properties are returning non optional values.

using kubb code generation the types generated are all optional, im not sure why this is happening but prevents me from smoothly intergrating the code generation into my project as i have to rewrite a huge amount of work

### How often does this bug happen?

None

### What is the expected behavior?

side by side, obviously kubb is soo much nice butt...

<img width="896" alt="image" src="https://github.com/kubb-project/kubb/assets/62810658/91cd06dc-f8c3-4f17-b80e-92813411bbf4">

kubb generated example, so close to being perfect
```
import { UpdateMarketResponse } from "./UpdateMarketResponse";
import type { ClientOrder } from "./ClientOrder";

 export type ClientOrderResponse = {
    clientOrder?: ClientOrder;
    /**
     * @type array | undefined
    */
    marketOrders?: UpdateMarketResponse[];
    /**
     * @type string | undefined
    */
    productTitle?: string;
    /**
     * @type string | undefined
    */
    productLogo?: string;
};
```

swagger docs
<img width="612" alt="image" src="https://github.com/kubb-project/kubb/assets/62810658/71095a52-745f-4f4f-9905-6436989d300a">

### Swagger/OpenAPI file?

[api-documentation.yaml.zip](https://github.com/kubb-project/kubb/files/14959568/api-documentation.yaml.zip)

**Comment by Samuel-Morgan-Tyghe** [comment]
```
{
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
      "format": "uuid"
    },
    "investorId": {
      "type": "string",
      "format": "uuid"
    },
    "userId": {
      "type": "string",
      "format": "uuid"
    },
    "walletAccountId": {
      "type": "string",
      "format": "uuid"
    },
    "paid": {
      "type": "number"
    },
    "price": {
      "type": "number"
    },
    "commitment": {
      "type": "number"
    },
    "broker": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid"
        },
        "name": {
          "type": "string",
          "enum": [
            "MODULR",
            "PLATFORM_ONE",
            "IQEQ",
            "AMITIS"
          ]
        },
        "type": {
          "type": "string",
          "enum": [
            "CASH",
            "PRIVATE",
            "PUBLIC"
          ]
        },
        "brokerAttributes": {
          "type": "object",
          "properties": {
            "validateUnitsAndPrice": {
              "type": "boolean"
            }
          },
          "x-readme-ref-name": "BrokerAttributes"
        },
        "offlineHolding": {
          "type": "boolean"
        }
      },
      "x-readme-ref-name": "Broker"
    },
    "groupId": {
      "type": "string",
      "format": "uuid"
    },
    "currency": {
      "type": "string",
      "enum": [
        "EUR",
        "GBP",
        "USD",
        "AUD"
      ]
    },
    "side": {
      "type": "string",
      "enum": [
        "BUY",
        "SELL"
      ]
    },
    "type": {
      "type": "string",
      "enum": [
        "MARKET",
        "LIMIT",
        "STOP_LOSS",
        "TAKE_PROFIT"
      ]
    },
    "timeInForce": {
      "type": "string",
      "enum": [
        "DAY",
        "GOOD_TILL_CANCEL",
        "FILL_OR_KILL",
        "MARKET_ON_OPEN",
        "LIMIT_ON_OPEN",
        "IMMEDIATE_OR_CANCEL"
      ]
    },
    "asset": {
      "type": "string",
      "format": "uuid",
      "deprecated": true
    },
    "assetId": {
      "type": "string",
      "format": "uuid"
    },
    "productId": {
      "type": "string",
      "format": "uuid"
    },
    "postedDate": {
      "type": "string",
      "format": "date-time"
    },
    "status": {
      "type": "string",
      "enum": [
        "CREATED",
        "PENDING",
        "SUBMITTED",
        "ORDERED",
        "CANCELLED",
        "FAILED",
        "COMPLETED"
      ]
    },
    "envelopeId": {
      "type": "string",
      "format": "uuid"
    },
    "completedAt": {
      "type": "string",
      "format": "date-time"
    },
    "updatedAt": {
      "type": "string",
      "format": "date-time"
    },
    "attributes": {
      "type": "object",
      "properties": {
        "sellPercentage": {
          "type": "number"
        }
      },
      "x-readme-ref-name": "ClientOrderAttributes"
    },
    "completed": {
      "type": "boolean"
    },
    "sellPercentage": {
      "type": "number"
    },
    "pendingSellOrder": {
      "type": "boolean"
    },
    "pendingBuyOrder": {
      "type": "boolean"
    },
    "pendingOrCompleted": {
      "type": "boolean"
    },
    "signedCommitmentAmount": {
      "type": "number"
    },
    "signedPaid": {
      "type": "number"
    }
  },
  "x-readme-ref-name": "ClientOrder"
}
```

**Comment by Samuel-Morgan-Tyghe** [comment]
Schema looks right, just the typescript plugin

**Comment by Nick-Lucas** [comment]
The schema is actually wrong. OpenAPI expects `required` to be set for non-nullable fields https://swagger.io/specification/

It's a bit backwards but your API is actually producing incorrect types because of a lack of annotations. Java for instance has a `@NotNull` decorator which needs to go everywhere because all Java types are nullable by default

**Comment by stijnvanhulle** [comment]
Hi @Samuel-Morgan-Tyghe, we are using `required` as the way to go for values to be optional or not. See https://json-schema.org/draft/2020-12/json-schema-validation#name-required. 

> Omitting this keyword has the same behavior as an empty array.

An empty array means that every property is optional and so not required. Not sure which other tool you use but they are probably not following that rule.

**Comment by Samuel-Morgan-Tyghe** [comment]
Anyway to override this? 

any lazy solutions rather than to apply `@NotNull `  everywhere on our Java BE ?

**Comment by Nick-Lucas** [comment]
There some more global solutions in SpringDoc etc, but I found they weren't appropriate in our case at work. Suggest you do some googling around it as it's a SpringDoc setup issue

That said Kubb would let you write your own generators, but it's probably similar effort to just fixing the backend

**Comment by Samuel-Morgan-Tyghe** [comment]
Thanks your advice, I'll take this to the team

The alternative tool is https://quicktype.io/

**Comment by vitorcamachoo** [comment]
This may be related to the origin of this "issue", but for a specific property that is string, nullable and not required, the non optional signal is not being set on the generated models:

Input:
```yaml
User:
      type: object
      properties:
        defaultProject:
          type: string
          format: uuid
          nullable: true
```

Output:
```ts
export type User = {
  /**
   * @type string, uuid
   */
  defaultProject: string | null
}
```

Expected Output:
```ts
export type User = {
  /**
   * @type string, uuid
   */
  defaultProject?: string | null
}
```

Is this the intended behaviour?
